import type { CountryPack, DueDiligenceRequirement } from './types';

/**
 * Country policy packs. These are reference defaults to get a tenant started,
 * not legal advice — every value can be overridden per tenant. Identifier
 * patterns are hints for UI placeholders; the core never rejects a value
 * because it fails a pattern (PRD §3.2.2).
 */

const SAT_SUN = [0, 6];

/** Evidence every jurisdiction asks for in some form. */
export const CORE_DUE_DILIGENCE: DueDiligenceRequirement[] = [
  {
    key: 'nda',
    label: { en: 'Non-Disclosure Agreement (NDA)', id: 'Perjanjian Kerahasiaan (NDA)' },
    required: true,
    aliases: ['NDA'],
    source: 'core',
  },
  {
    key: 'vendor_assessment',
    label: { en: 'Vendor assessment form', id: 'Formulir penilaian vendor' },
    required: false,
    aliases: ['Vendor assessment form'],
    source: 'core',
  },
  {
    key: 'beneficial_ownership',
    label: { en: 'Beneficial ownership declaration', id: 'Pernyataan pemilik manfaat' },
    required: false,
    source: 'core',
  },
  {
    key: 'bank_account_confirmation',
    label: { en: 'Bank account confirmation letter', id: 'Surat konfirmasi rekening bank' },
    required: false,
    source: 'core',
  },
  {
    key: 'termination_notice',
    label: { en: 'Termination notice', id: 'Surat pemberitahuan pengakhiran' },
    required: false,
    aliases: ['Termination notice'],
    source: 'core',
  },
];

const tax = (key: string, label: string, example?: string, pattern?: string) => ({
  key,
  label,
  category: 'tax' as const,
  appliesTo: ['organization' as const, 'individual' as const],
  example,
  pattern,
  sensitivity: 'confidential' as const,
});
const reg = (key: string, label: string, example?: string, pattern?: string) => ({
  key,
  label,
  category: 'registration' as const,
  appliesTo: ['organization' as const],
  example,
  pattern,
  sensitivity: 'internal' as const,
});
const personal = (key: string, label: string) => ({
  key,
  label,
  category: 'personal' as const,
  appliesTo: ['individual' as const],
  sensitivity: 'restricted' as const,
});
const doc = (
  key: string,
  en: string,
  id: string | undefined,
  opts: Partial<DueDiligenceRequirement> = {},
): DueDiligenceRequirement => ({ key, label: { en, id }, required: false, source: 'country', ...opts });

export const COUNTRY_PACKS: CountryPack[] = [
  {
    code: 'INTL',
    name: 'International (jurisdiction-neutral)',
    region: 'International',
    defaultCurrency: 'USD',
    formattingLocale: 'en-US',
    timezone: 'UTC',
    weekend: SAT_SUN,
    callingCode: '',
    legalForms: ['Company', 'Partnership', 'Sole proprietor', 'Government entity', 'Nonprofit', 'Individual'],
    identifierSchemes: [
      tax('tax_id', 'Tax identification number'),
      reg('company_registration', 'Company registration number'),
      reg('lei', 'Legal Entity Identifier (LEI)', '5493001KJTIIGC8Y1R12', '^[A-Z0-9]{20}$'),
    ],
    dueDiligence: [
      doc('certificate_of_incorporation', 'Certificate of incorporation / registration', 'Sertifikat pendirian / registrasi'),
      doc('tax_registration', 'Tax registration certificate', 'Sertifikat registrasi pajak'),
    ],
    governingLaw: { en: 'the laws agreed by the Parties', id: 'hukum yang disepakati Para Pihak' },
    disputeVenue: { en: 'the courts agreed by the Parties', id: 'pengadilan yang disepakati Para Pihak' },
    dataProtectionLaw: 'applicable data protection laws',
    indirectTaxName: 'VAT',
  },
  {
    code: 'ID',
    name: 'Indonesia',
    region: 'Southeast Asia',
    defaultCurrency: 'IDR',
    formattingLocale: 'id-ID',
    timezone: 'Asia/Jakarta',
    weekend: SAT_SUN,
    callingCode: '62',
    legalForms: ['PT (Perseroan Terbatas)', 'PT Tbk', 'CV', 'Firma', 'Koperasi', 'Yayasan', 'Perorangan'],
    identifierSchemes: [
      tax('id_npwp', 'NPWP (Nomor Pokok Wajib Pajak)', '01.234.567.8-012.000'),
      reg('id_nib', 'NIB (Nomor Induk Berusaha)', '9120001234567', '^\\d{13}$'),
      reg('id_ahu', 'Nomor SK Kemenkumham (AHU)', 'AHU-00123.AH.01.01'),
      personal('id_nik', 'NIK (Nomor Induk Kependudukan)'),
    ],
    dueDiligence: [
      doc('id_akta', 'Deed of establishment & amendments (Akta Pendirian)', 'Akta Pendirian & Perubahan', {
        aliases: ['Akta Pendirian', 'Akta Pendirian & Perubahan', 'Akta'],
      }),
      doc('id_nib', 'Business identification number (NIB) & business licence', 'NIB & Izin Usaha', {
        aliases: ['NIB/SIUP', 'NIB & Izin Usaha', 'NIB', 'SIUP', 'Business license'],
        expires: true,
      }),
      doc('id_npwp', 'Tax registration (NPWP)', 'NPWP Perusahaan', { aliases: ['NPWP', 'NPWP Perusahaan'] }),
      doc('id_director_id', 'Directors & PIC identity cards (KTP)', 'KTP Direksi & PIC', {
        aliases: ['KTP Direksi & PIC', 'KTP'],
      }),
      doc('id_cor', 'Certificate of Residence (COR) for tax treaty', 'Certificate of Residence (COR)', {
        aliases: ['COR'],
        foreignCounterpartyOnly: true,
        expires: true,
      }),
      doc('id_dgt', 'DGT form for treaty withholding relief', 'Formulir DGT', {
        aliases: ['DGT'],
        foreignCounterpartyOnly: true,
        expires: true,
      }),
    ],
    governingLaw: { en: 'the laws of the Republic of Indonesia', id: 'hukum Negara Republik Indonesia' },
    disputeVenue: { en: 'the District Court of South Jakarta', id: 'Pengadilan Negeri Jakarta Selatan' },
    dataProtectionLaw: 'Law No. 27 of 2022 on Personal Data Protection (UU PDP)',
    indirectTaxName: 'VAT (PPN)',
    stampDutyConvention: {
      en: 'executed in two originals bearing sufficient stamp duty (meterai)',
      id: 'dibuat dalam 2 (dua) rangkap asli bermeterai cukup',
    },
    regulators: {
      financial_services: ['Otoritas Jasa Keuangan (OJK)', 'Bank Indonesia'],
      healthcare: ['Kementerian Kesehatan', 'BPOM'],
      technology: ['Kementerian Komunikasi dan Digital (Komdigi)'],
    },
  },
  {
    code: 'SG',
    name: 'Singapore',
    region: 'Southeast Asia',
    defaultCurrency: 'SGD',
    formattingLocale: 'en-SG',
    timezone: 'Asia/Singapore',
    weekend: SAT_SUN,
    callingCode: '65',
    legalForms: ['Private Limited (Pte. Ltd.)', 'Public Company (Ltd.)', 'Limited Liability Partnership (LLP)', 'Sole Proprietorship', 'Partnership'],
    identifierSchemes: [
      reg('sg_uen', 'Unique Entity Number (UEN)', '201912345K'),
      tax('sg_gst', 'GST registration number', 'M90312345A'),
      personal('sg_nric', 'NRIC / FIN'),
    ],
    dueDiligence: [
      doc('sg_bizfile', 'ACRA BizFile business profile', 'Profil bisnis ACRA BizFile', { expires: true }),
      doc('sg_gst_certificate', 'GST registration certificate', 'Sertifikat registrasi GST'),
    ],
    governingLaw: { en: 'the laws of the Republic of Singapore', id: 'hukum Republik Singapura' },
    disputeVenue: { en: 'the Singapore International Arbitration Centre (SIAC)', id: 'Singapore International Arbitration Centre (SIAC)' },
    dataProtectionLaw: 'Personal Data Protection Act 2012 (PDPA)',
    indirectTaxName: 'GST',
    regulators: {
      financial_services: ['Monetary Authority of Singapore (MAS)'],
      healthcare: ['Ministry of Health (MOH)', 'Health Sciences Authority (HSA)'],
      technology: ['Infocomm Media Development Authority (IMDA)', 'Personal Data Protection Commission (PDPC)'],
    },
  },
  {
    code: 'MY',
    name: 'Malaysia',
    region: 'Southeast Asia',
    defaultCurrency: 'MYR',
    formattingLocale: 'en-MY',
    timezone: 'Asia/Kuala_Lumpur',
    weekend: SAT_SUN,
    callingCode: '60',
    legalForms: ['Sendirian Berhad (Sdn. Bhd.)', 'Berhad (Bhd.)', 'Limited Liability Partnership (PLT)', 'Sole Proprietorship', 'Partnership'],
    identifierSchemes: [
      reg('my_ssm', 'SSM company registration number', '202001012345'),
      tax('my_tin', 'Tax Identification Number (TIN)', 'C1234567890'),
      tax('my_sst', 'SST registration number'),
      personal('my_nric', 'MyKad number'),
    ],
    dueDiligence: [
      doc('my_ssm_profile', 'SSM company profile / certificate of incorporation', 'Profil perusahaan SSM', { expires: true }),
      doc('my_sst_certificate', 'SST registration certificate', 'Sertifikat registrasi SST'),
    ],
    governingLaw: { en: 'the laws of Malaysia', id: 'hukum Malaysia' },
    disputeVenue: { en: 'the Asian International Arbitration Centre (AIAC), Kuala Lumpur', id: 'Asian International Arbitration Centre (AIAC), Kuala Lumpur' },
    dataProtectionLaw: 'Personal Data Protection Act 2010 (PDPA)',
    indirectTaxName: 'SST',
    regulators: {
      financial_services: ['Bank Negara Malaysia (BNM)', 'Securities Commission Malaysia'],
      healthcare: ['Ministry of Health Malaysia'],
    },
  },
  {
    code: 'TH',
    name: 'Thailand',
    region: 'Southeast Asia',
    defaultCurrency: 'THB',
    formattingLocale: 'en-TH',
    timezone: 'Asia/Bangkok',
    weekend: SAT_SUN,
    callingCode: '66',
    legalForms: ['Company Limited (Co., Ltd.)', 'Public Company Limited (PCL)', 'Limited Partnership', 'Sole Proprietorship'],
    identifierSchemes: [
      tax('th_tax_id', '13-digit Tax ID / juristic person number', '0105561234567', '^\\d{13}$'),
      personal('th_citizen_id', 'Thai citizen ID'),
    ],
    dueDiligence: [
      doc('th_dbd_affidavit', 'DBD company affidavit (certificate of registration)', 'Affidavit perusahaan DBD', { expires: true }),
      doc('th_vat_certificate', 'VAT registration certificate (Por Por 20)', 'Sertifikat registrasi VAT (Por Por 20)'),
    ],
    governingLaw: { en: 'the laws of the Kingdom of Thailand', id: 'hukum Kerajaan Thailand' },
    disputeVenue: { en: 'the Thai Arbitration Institute (TAI), Bangkok', id: 'Thai Arbitration Institute (TAI), Bangkok' },
    dataProtectionLaw: 'Personal Data Protection Act B.E. 2562 (2019)',
    indirectTaxName: 'VAT',
    regulators: {
      financial_services: ['Bank of Thailand', 'Securities and Exchange Commission Thailand'],
    },
  },
  {
    code: 'VN',
    name: 'Vietnam',
    region: 'Southeast Asia',
    defaultCurrency: 'VND',
    formattingLocale: 'vi-VN',
    timezone: 'Asia/Ho_Chi_Minh',
    weekend: SAT_SUN,
    callingCode: '84',
    legalForms: ['Limited Liability Company (LLC)', 'Joint Stock Company (JSC)', 'Partnership', 'Private Enterprise'],
    identifierSchemes: [
      tax('vn_tax_code', 'Enterprise code / tax code (MST)', '0312345678', '^\\d{10}(-\\d{3})?$'),
      personal('vn_citizen_id', 'Citizen identity card number'),
    ],
    dueDiligence: [
      doc('vn_erc', 'Enterprise Registration Certificate (ERC)', 'Enterprise Registration Certificate (ERC)'),
      doc('vn_irc', 'Investment Registration Certificate (foreign-invested entities)', 'Investment Registration Certificate', {
        foreignCounterpartyOnly: true,
      }),
    ],
    governingLaw: { en: 'the laws of the Socialist Republic of Vietnam', id: 'hukum Republik Sosialis Vietnam' },
    disputeVenue: { en: 'the Vietnam International Arbitration Centre (VIAC)', id: 'Vietnam International Arbitration Centre (VIAC)' },
    dataProtectionLaw: 'Vietnamese personal data protection law and its implementing decrees',
    indirectTaxName: 'VAT',
    regulators: {
      financial_services: ['State Bank of Vietnam'],
    },
  },
  {
    code: 'PH',
    name: 'Philippines',
    region: 'Southeast Asia',
    defaultCurrency: 'PHP',
    formattingLocale: 'en-PH',
    timezone: 'Asia/Manila',
    weekend: SAT_SUN,
    callingCode: '63',
    legalForms: ['Stock Corporation', 'One Person Corporation (OPC)', 'Partnership', 'Sole Proprietorship'],
    identifierSchemes: [
      tax('ph_tin', 'BIR Taxpayer Identification Number (TIN)', '123-456-789-000'),
      reg('ph_sec', 'SEC registration number'),
      reg('ph_dti', 'DTI business name registration (sole proprietors)'),
    ],
    dueDiligence: [
      doc('ph_sec_certificate', 'SEC certificate of incorporation', 'Sertifikat inkorporasi SEC'),
      doc('ph_bir_2303', 'BIR Certificate of Registration (Form 2303)', 'BIR Certificate of Registration (Form 2303)'),
      doc('ph_business_permit', "Mayor's / business permit", 'Izin usaha daerah', { expires: true }),
    ],
    governingLaw: { en: 'the laws of the Republic of the Philippines', id: 'hukum Republik Filipina' },
    disputeVenue: { en: 'the Philippine Dispute Resolution Center (PDRCI)', id: 'Philippine Dispute Resolution Center (PDRCI)' },
    dataProtectionLaw: 'Data Privacy Act of 2012 (Republic Act No. 10173)',
    indirectTaxName: 'VAT',
    regulators: {
      financial_services: ['Bangko Sentral ng Pilipinas (BSP)', 'Securities and Exchange Commission'],
    },
  },
  {
    code: 'IN',
    name: 'India',
    region: 'South Asia',
    defaultCurrency: 'INR',
    formattingLocale: 'en-IN',
    timezone: 'Asia/Kolkata',
    weekend: SAT_SUN,
    callingCode: '91',
    legalForms: ['Private Limited Company', 'Public Limited Company', 'Limited Liability Partnership (LLP)', 'One Person Company', 'Sole Proprietorship', 'Partnership Firm'],
    identifierSchemes: [
      tax('in_pan', 'Permanent Account Number (PAN)', 'AAACA1234A', '^[A-Z]{5}\\d{4}[A-Z]$'),
      tax('in_gstin', 'GSTIN', '27AAACA1234A1Z5', '^\\d{2}[A-Z]{5}\\d{4}[A-Z][A-Z0-9]Z[A-Z0-9]$'),
      reg('in_cin', 'Corporate Identification Number (CIN)', 'U72900MH2015PTC123456'),
      personal('in_aadhaar', 'Aadhaar number'),
    ],
    dueDiligence: [
      doc('in_incorporation', 'Certificate of incorporation (MCA)', 'Sertifikat inkorporasi (MCA)'),
      doc('in_pan_card', 'PAN card copy', 'Salinan kartu PAN'),
      doc('in_gst_certificate', 'GST registration certificate', 'Sertifikat registrasi GST'),
      doc('in_msme', 'Udyam (MSME) registration, if applicable', 'Registrasi Udyam (MSME), bila ada'),
    ],
    governingLaw: { en: 'the laws of India', id: 'hukum India' },
    disputeVenue: { en: 'arbitration seated in Mumbai under the Arbitration and Conciliation Act, 1996', id: 'arbitrase berkedudukan di Mumbai berdasarkan Arbitration and Conciliation Act 1996' },
    dataProtectionLaw: 'Digital Personal Data Protection Act, 2023 (DPDP Act)',
    indirectTaxName: 'GST',
    regulators: {
      financial_services: ['Reserve Bank of India (RBI)', 'Securities and Exchange Board of India (SEBI)'],
      healthcare: ['Central Drugs Standard Control Organisation (CDSCO)'],
    },
  },
  {
    code: 'JP',
    name: 'Japan',
    region: 'East Asia',
    defaultCurrency: 'JPY',
    formattingLocale: 'ja-JP',
    timezone: 'Asia/Tokyo',
    weekend: SAT_SUN,
    callingCode: '81',
    legalForms: ['Kabushiki Kaisha (KK)', 'Godo Kaisha (GK)', 'Branch office', 'Sole proprietor'],
    identifierSchemes: [
      reg('jp_corporate_number', 'Corporate Number (Hojin Bango)', '1234567890123', '^\\d{13}$'),
      tax('jp_invoice_registration', 'Qualified invoice issuer registration number', 'T1234567890123', '^T\\d{13}$'),
      personal('jp_my_number', 'My Number'),
    ],
    dueDiligence: [
      doc('jp_registry_certificate', 'Certificate of registered matters (Tokibo Tohon)', 'Sertifikat registrasi perusahaan (Tokibo Tohon)', { expires: true }),
      doc('jp_invoice_registration', 'Qualified invoice issuer registration notice', 'Pemberitahuan registrasi penerbit faktur'),
    ],
    governingLaw: { en: 'the laws of Japan', id: 'hukum Jepang' },
    disputeVenue: { en: 'the Tokyo District Court', id: 'Pengadilan Distrik Tokyo' },
    dataProtectionLaw: 'Act on the Protection of Personal Information (APPI)',
    indirectTaxName: 'consumption tax',
    regulators: {
      financial_services: ['Financial Services Agency (FSA)'],
      healthcare: ['Ministry of Health, Labour and Welfare (MHLW)', 'PMDA'],
    },
  },
  {
    code: 'KR',
    name: 'South Korea',
    region: 'East Asia',
    defaultCurrency: 'KRW',
    formattingLocale: 'ko-KR',
    timezone: 'Asia/Seoul',
    weekend: SAT_SUN,
    callingCode: '82',
    legalForms: ['Chusik Hoesa (Co., Ltd.)', 'Yuhan Hoesa (LLC)', 'Branch office', 'Sole proprietor'],
    identifierSchemes: [
      tax('kr_brn', 'Business Registration Number', '123-45-67890', '^\\d{3}-?\\d{2}-?\\d{5}$'),
      reg('kr_crn', 'Corporate Registration Number', '110111-1234567'),
      personal('kr_rrn', 'Resident Registration Number'),
    ],
    dueDiligence: [
      doc('kr_business_registration', 'Business registration certificate', 'Sertifikat registrasi usaha'),
      doc('kr_corporate_registry', 'Corporate registry certificate', 'Sertifikat registri korporasi', { expires: true }),
    ],
    governingLaw: { en: 'the laws of the Republic of Korea', id: 'hukum Republik Korea' },
    disputeVenue: { en: 'the Korean Commercial Arbitration Board (KCAB)', id: 'Korean Commercial Arbitration Board (KCAB)' },
    dataProtectionLaw: 'Personal Information Protection Act (PIPA)',
    indirectTaxName: 'VAT',
    regulators: {
      financial_services: ['Financial Services Commission (FSC)', 'Financial Supervisory Service (FSS)'],
    },
  },
  {
    code: 'CN',
    name: 'China (Mainland)',
    region: 'East Asia',
    defaultCurrency: 'CNY',
    formattingLocale: 'zh-CN',
    timezone: 'Asia/Shanghai',
    weekend: SAT_SUN,
    callingCode: '86',
    legalForms: ['Limited Liability Company', 'Company Limited by Shares', 'Wholly Foreign-Owned Enterprise (WFOE)', 'Joint Venture'],
    identifierSchemes: [
      reg('cn_uscc', 'Unified Social Credit Code (USCC)', '91310000MA1FL1234X', '^[0-9A-HJ-NPQRTUWXY]{2}\\d{6}[0-9A-HJ-NPQRTUWXY]{10}$'),
      personal('cn_resident_id', 'Resident identity card number'),
    ],
    dueDiligence: [
      doc('cn_business_licence', 'Business licence (Yingye Zhizhao)', 'Izin usaha (Yingye Zhizhao)'),
    ],
    governingLaw: { en: "the laws of the People's Republic of China", id: 'hukum Republik Rakyat Tiongkok' },
    disputeVenue: { en: 'the China International Economic and Trade Arbitration Commission (CIETAC)', id: 'CIETAC' },
    dataProtectionLaw: 'Personal Information Protection Law (PIPL)',
    indirectTaxName: 'VAT',
    regulators: {
      financial_services: ["People's Bank of China", 'National Financial Regulatory Administration'],
    },
  },
  {
    code: 'HK',
    name: 'Hong Kong SAR',
    region: 'East Asia',
    defaultCurrency: 'HKD',
    formattingLocale: 'en-HK',
    timezone: 'Asia/Hong_Kong',
    weekend: SAT_SUN,
    callingCode: '852',
    legalForms: ['Private Company Limited by Shares', 'Public Company', 'Partnership', 'Sole Proprietorship'],
    identifierSchemes: [
      reg('hk_brn', 'Business Registration Number (BRN)', '12345678'),
      reg('hk_crn', 'Company Registration Number (CRN)', '1234567'),
      personal('hk_hkid', 'HKID number'),
    ],
    dueDiligence: [
      doc('hk_br_certificate', 'Business Registration Certificate', 'Business Registration Certificate', { expires: true }),
      doc('hk_incorporation', 'Certificate of incorporation', 'Sertifikat inkorporasi'),
    ],
    governingLaw: { en: 'the laws of the Hong Kong Special Administrative Region', id: 'hukum Daerah Administratif Khusus Hong Kong' },
    disputeVenue: { en: 'the Hong Kong International Arbitration Centre (HKIAC)', id: 'Hong Kong International Arbitration Centre (HKIAC)' },
    dataProtectionLaw: 'Personal Data (Privacy) Ordinance (Cap. 486)',
    indirectTaxName: 'sales tax',
    regulators: {
      financial_services: ['Hong Kong Monetary Authority (HKMA)', 'Securities and Futures Commission (SFC)'],
    },
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    region: 'Middle East',
    defaultCurrency: 'AED',
    formattingLocale: 'en-AE',
    timezone: 'Asia/Dubai',
    weekend: SAT_SUN,
    callingCode: '971',
    legalForms: ['Limited Liability Company (LLC)', 'Free Zone Establishment (FZE)', 'Free Zone Company (FZCO)', 'Branch office', 'Sole Establishment'],
    identifierSchemes: [
      tax('ae_trn', 'Tax Registration Number (TRN)', '100123456700003', '^\\d{15}$'),
      reg('ae_trade_licence', 'Trade licence number'),
      personal('ae_emirates_id', 'Emirates ID'),
    ],
    dueDiligence: [
      doc('ae_trade_licence', 'Trade licence', 'Trade licence', { expires: true }),
      doc('ae_vat_certificate', 'VAT registration certificate', 'Sertifikat registrasi VAT'),
    ],
    governingLaw: { en: 'the laws of the United Arab Emirates', id: 'hukum Uni Emirat Arab' },
    disputeVenue: { en: 'the Dubai International Arbitration Centre', id: 'Dubai International Arbitration Centre' },
    dataProtectionLaw: 'Federal Decree-Law No. 45 of 2021 on the Protection of Personal Data',
    indirectTaxName: 'VAT',
    regulators: {
      financial_services: ['Central Bank of the UAE', 'Dubai Financial Services Authority (DFSA)'],
    },
  },
];
