import type { DueDiligenceRequirement, IndustryPack } from './types';

const doc = (
  key: string,
  en: string,
  id: string,
  opts: Partial<DueDiligenceRequirement> = {},
): DueDiligenceRequirement => ({ key, label: { en, id }, required: false, source: 'industry', ...opts });

const GENERIC_PRICING = ['Fixed Fee', 'Time & Materials', 'Milestone-based', 'Subscription', 'Unit Price', 'Revenue Share'];

export const INDUSTRY_PACKS: IndustryPack[] = [
  {
    key: 'general',
    name: { en: 'General / Multi-industry', id: 'Umum / Lintas industri' },
    partnerCategories: ['Supplier', 'Service Provider', 'Consultant', 'Customer', 'Distributor', 'Partner'],
    dueDiligence: [],
    commercialDocument: {
      label: 'Statement of Work',
      plural: 'Statements of Work',
      prefix: 'SOW',
      pricingModels: GENERIC_PRICING,
      channelLabel: 'Scope / Workstream',
      channelPlaceholder: 'e.g. Implementation phase 1',
    },
    aiReviewFocus: ['limitation of liability', 'termination and notice', 'confidentiality', 'data protection', 'payment terms', 'dispute resolution'],
    newsTopic: 'commercial contract and corporate compliance regulation',
  },
  {
    key: 'financial_services',
    name: { en: 'Financial Services & Fintech', id: 'Jasa Keuangan & Fintech' },
    partnerCategories: ['Payment Provider', 'Credit Bureau', 'Collection Agency', 'Core Banking Vendor', 'Cloud Provider', 'Marketing Partner', 'KYC Provider'],
    dueDiligence: [
      doc('fs_aml_questionnaire', 'AML/CFT & sanctions questionnaire', 'Kuesioner APU-PPT & sanksi', { required: true }),
      doc('fs_outsourcing_assessment', 'Material outsourcing / third-party risk assessment', 'Penilaian risiko alih daya pihak ketiga'),
      doc('fs_business_continuity', 'Business continuity & disaster recovery plan', 'Rencana keberlangsungan usaha & pemulihan bencana'),
      doc('fs_security_certification', 'Information security certification (e.g. ISO 27001, PCI DSS)', 'Sertifikasi keamanan informasi (mis. ISO 27001, PCI DSS)', { expires: true }),
    ],
    commercialDocument: {
      label: 'Service Order',
      plural: 'Service Orders',
      prefix: 'SO',
      pricingModels: ['Fixed Fee', 'Per Transaction', 'Commission Fee', 'Revenue Share', 'Subscription', 'Tiered Volume'],
      channelLabel: 'Service / Product line',
      channelPlaceholder: 'e.g. Payment gateway, Credit scoring API',
    },
    aiReviewFocus: [
      'regulator audit and inspection rights',
      'outsourcing and third-party risk requirements',
      'customer data confidentiality and data localisation',
      'anti-money-laundering and sanctions obligations',
      'business continuity and exit management',
      'consumer protection',
    ],
    newsTopic: 'financial services and fintech regulation',
  },
  {
    key: 'technology',
    name: { en: 'Technology & SaaS', id: 'Teknologi & SaaS' },
    partnerCategories: ['Cloud Infrastructure', 'SaaS Vendor', 'Reseller', 'Systems Integrator', 'Data Processor', 'Customer'],
    dueDiligence: [
      doc('tech_dpa', 'Data Processing Agreement (DPA)', 'Perjanjian Pemrosesan Data (DPA)', { required: true }),
      doc('tech_security_questionnaire', 'Security questionnaire (e.g. CAIQ, SIG Lite)', 'Kuesioner keamanan (mis. CAIQ, SIG Lite)'),
      doc('tech_soc2_iso', 'SOC 2 report or ISO 27001 certificate', 'Laporan SOC 2 atau sertifikat ISO 27001', { expires: true }),
      doc('tech_subprocessors', 'Sub-processor list', 'Daftar sub-pemroses'),
    ],
    commercialDocument: {
      label: 'Order Form',
      plural: 'Order Forms',
      prefix: 'OF',
      pricingModels: ['Subscription (per seat)', 'Subscription (flat)', 'Usage-based', 'One-time Licence', 'Professional Services', 'Tiered Volume'],
      channelLabel: 'Product / Plan',
      channelPlaceholder: 'e.g. Enterprise plan, 250 seats',
    },
    aiReviewFocus: ['service levels and service credits', 'data processing and cross-border transfer', 'security incident notification', 'intellectual property and licence scope', 'limitation of liability', 'auto-renewal and price increases'],
    newsTopic: 'technology, data protection and cybersecurity regulation',
  },
  {
    key: 'healthcare',
    name: { en: 'Healthcare & Life Sciences', id: 'Kesehatan & Ilmu Hayati' },
    partnerCategories: ['Clinical Research Organisation', 'Medical Device Supplier', 'Pharmaceutical Supplier', 'Laboratory', 'Health IT Vendor', 'Hospital / Clinic'],
    dueDiligence: [
      doc('hc_licence', 'Healthcare facility / product licence', 'Izin fasilitas / produk kesehatan', { required: true, expires: true }),
      doc('hc_gxp', 'GxP / quality certification (e.g. ISO 13485, GMP)', 'Sertifikasi GxP / mutu (mis. ISO 13485, CPOB)', { expires: true }),
      doc('hc_health_data_agreement', 'Health data protection agreement', 'Perjanjian perlindungan data kesehatan'),
      doc('hc_insurance', 'Professional liability insurance', 'Asuransi tanggung gugat profesional', { expires: true }),
    ],
    commercialDocument: {
      label: 'Service Agreement Schedule',
      plural: 'Service Agreement Schedules',
      prefix: 'SAS',
      pricingModels: ['Fixed Fee', 'Per Patient', 'Per Procedure', 'Per Unit', 'Milestone-based'],
      channelLabel: 'Programme / Site',
      channelPlaceholder: 'e.g. Phase II trial, Site 04',
    },
    aiReviewFocus: ['patient and health data protection', 'regulatory licensing and product liability', 'pharmacovigilance and adverse event reporting', 'anti-bribery in healthcare', 'insurance and indemnity'],
    newsTopic: 'healthcare, medical device and pharmaceutical regulation',
  },
  {
    key: 'manufacturing',
    name: { en: 'Manufacturing & Supply Chain', id: 'Manufaktur & Rantai Pasok' },
    partnerCategories: ['Raw Material Supplier', 'Component Supplier', 'Contract Manufacturer', 'Logistics Provider', 'Distributor', 'Maintenance Contractor'],
    dueDiligence: [
      doc('mfg_quality_cert', 'Quality management certificate (e.g. ISO 9001)', 'Sertifikat manajemen mutu (mis. ISO 9001)', { expires: true }),
      doc('mfg_hse', 'Health, safety & environment compliance evidence', 'Bukti kepatuhan K3 & lingkungan'),
      doc('mfg_supplier_code', 'Signed supplier code of conduct', 'Kode etik pemasok yang ditandatangani', { required: true }),
      doc('mfg_product_liability', 'Product liability insurance', 'Asuransi tanggung gugat produk', { expires: true }),
    ],
    commercialDocument: {
      label: 'Purchase Order',
      plural: 'Purchase Orders',
      prefix: 'PO',
      pricingModels: ['Unit Price', 'Fixed Price', 'Cost Plus', 'Volume Discount', 'Consignment'],
      channelLabel: 'Item / Category',
      channelPlaceholder: 'e.g. Steel coil grade A',
    },
    aiReviewFocus: ['delivery terms and Incoterms', 'warranty and product liability', 'quality acceptance and rejection', 'force majeure and supply continuity', 'health, safety and environment'],
    newsTopic: 'manufacturing, trade and supply-chain regulation',
  },
  {
    key: 'retail',
    name: { en: 'Retail & E-commerce', id: 'Ritel & E-commerce' },
    partnerCategories: ['Merchant', 'Brand Principal', 'Fulfilment Partner', 'Payment Provider', 'Marketplace', 'Logistics Provider'],
    dueDiligence: [
      doc('retail_brand_authorisation', 'Brand authorisation / distribution letter', 'Surat penunjukan distributor / otorisasi merek'),
      doc('retail_product_compliance', 'Product safety & labelling compliance', 'Kepatuhan keamanan & label produk'),
    ],
    commercialDocument: {
      label: 'Purchase Order',
      plural: 'Purchase Orders',
      prefix: 'PO',
      pricingModels: ['Unit Price', 'Consignment', 'Commission Fee', 'Revenue Share', 'Listing Fee'],
      channelLabel: 'Sales channel',
      channelPlaceholder: 'e.g. Online marketplace, Flagship store',
    },
    aiReviewFocus: ['consumer protection and returns', 'pricing and exclusivity', 'intellectual property and brand use', 'data protection', 'payment and settlement terms'],
    newsTopic: 'retail, consumer protection and e-commerce regulation',
  },
  {
    key: 'media_advertising',
    name: { en: 'Media & Advertising', id: 'Media & Periklanan' },
    partnerCategories: ['Advertising', 'Media Placement', 'AdTech', 'Content', 'Influencer / KOL', 'Agency'],
    dueDiligence: [
      doc('media_placement_docs', 'Placement documentation', 'Dokumentasi penempatan', { aliases: ['Placement Documentation'] }),
      doc('media_brand_safety', 'Brand safety & ad-fraud policy', 'Kebijakan brand safety & ad-fraud'),
    ],
    commercialDocument: {
      label: 'Insertion Order',
      plural: 'Insertion Orders',
      prefix: 'IO',
      pricingModels: ['CPM', 'CPC', 'CPA', 'Flat Fee', 'Revenue Share', 'Fixed Package', 'Commission Fee'],
      channelLabel: 'Media channel',
      channelPlaceholder: 'e.g. Digital banner & social media',
    },
    aiReviewFocus: ['delivery and make-good terms', 'brand safety and content standards', 'advertising and consumer protection rules', 'data and tracking consent', 'intellectual property in creatives'],
    newsTopic: 'advertising, media and digital marketing regulation',
  },
  {
    key: 'professional_services',
    name: { en: 'Professional Services', id: 'Jasa Profesional' },
    partnerCategories: ['Consultant', 'Law Firm', 'Audit Firm', 'Contractor', 'Staffing Agency', 'Client'],
    dueDiligence: [
      doc('ps_professional_indemnity', 'Professional indemnity insurance', 'Asuransi indemnitas profesional', { expires: true }),
      doc('ps_conflict_check', 'Conflict of interest declaration', 'Pernyataan benturan kepentingan', { required: true }),
    ],
    commercialDocument: {
      label: 'Statement of Work',
      plural: 'Statements of Work',
      prefix: 'SOW',
      pricingModels: ['Time & Materials', 'Fixed Fee', 'Retainer', 'Milestone-based', 'Success Fee'],
      channelLabel: 'Engagement',
      channelPlaceholder: 'e.g. Tax advisory FY2026',
    },
    aiReviewFocus: ['scope and change control', 'professional liability caps', 'conflicts and independence', 'confidentiality and privilege', 'personnel and non-solicitation'],
    newsTopic: 'professional services and corporate governance regulation',
  },
  {
    key: 'logistics',
    name: { en: 'Logistics & Transportation', id: 'Logistik & Transportasi' },
    partnerCategories: ['Carrier', 'Freight Forwarder', 'Warehouse Operator', 'Customs Broker', 'Last-mile Partner'],
    dueDiligence: [
      doc('log_operating_licence', 'Transport / forwarding operating licence', 'Izin operasional angkutan / forwarding', { required: true, expires: true }),
      doc('log_cargo_insurance', 'Cargo liability insurance', 'Asuransi tanggung gugat kargo', { expires: true }),
    ],
    commercialDocument: {
      label: 'Service Order',
      plural: 'Service Orders',
      prefix: 'SO',
      pricingModels: ['Per Shipment', 'Per Kilogram', 'Per Pallet / Month', 'Fixed Fee', 'Fuel Surcharge Indexed'],
      channelLabel: 'Lane / Service',
      channelPlaceholder: 'e.g. SIN–JKT sea freight',
    },
    aiReviewFocus: ['liability limits for loss and damage', 'Incoterms and transfer of risk', 'customs and sanctions compliance', 'service levels and penalties', 'insurance'],
    newsTopic: 'logistics, customs and transportation regulation',
  },
  {
    key: 'energy',
    name: { en: 'Energy & Resources', id: 'Energi & Sumber Daya' },
    partnerCategories: ['EPC Contractor', 'Equipment Supplier', 'Offtaker', 'Operator', 'Consultant'],
    dueDiligence: [
      doc('energy_hse', 'HSE management system certificate (e.g. ISO 45001, ISO 14001)', 'Sertifikat sistem manajemen K3L (mis. ISO 45001, ISO 14001)', { required: true, expires: true }),
      doc('energy_permits', 'Operating permits and concessions', 'Izin operasi dan konsesi', { expires: true }),
    ],
    commercialDocument: {
      label: 'Work Order',
      plural: 'Work Orders',
      prefix: 'WO',
      pricingModels: ['Lump Sum', 'Unit Rate', 'Cost Reimbursable', 'Day Rate', 'Take-or-Pay'],
      channelLabel: 'Site / Asset',
      channelPlaceholder: 'e.g. Plant B maintenance',
    },
    aiReviewFocus: ['health, safety and environment', 'permits and local content', 'force majeure', 'liquidated damages', 'indemnities and insurance'],
    newsTopic: 'energy, mining and environmental regulation',
  },
  {
    key: 'education',
    name: { en: 'Education', id: 'Pendidikan' },
    partnerCategories: ['Content Provider', 'EdTech Vendor', 'Institution', 'Trainer', 'Facility Provider'],
    dueDiligence: [
      doc('edu_child_safety', 'Child safeguarding policy', 'Kebijakan perlindungan anak'),
      doc('edu_accreditation', 'Accreditation / licence', 'Akreditasi / izin', { expires: true }),
    ],
    commercialDocument: {
      label: 'Service Order',
      plural: 'Service Orders',
      prefix: 'SO',
      pricingModels: ['Per Learner', 'Per Course', 'Subscription', 'Fixed Fee'],
      channelLabel: 'Programme',
      channelPlaceholder: 'e.g. Semester 1 language course',
    },
    aiReviewFocus: ['student data protection', 'safeguarding', 'intellectual property in materials', 'accreditation obligations'],
    newsTopic: 'education and student data regulation',
  },
  {
    key: 'nonprofit',
    name: { en: 'Nonprofit & NGO', id: 'Nirlaba & LSM' },
    partnerCategories: ['Donor', 'Implementing Partner', 'Grantee', 'Supplier', 'Government Agency'],
    dueDiligence: [
      doc('np_registration', 'Charity / NGO registration', 'Registrasi yayasan / LSM'),
      doc('np_anti_terror_financing', 'Counter-terrorism financing & sanctions screening', 'Penyaringan pendanaan terorisme & sanksi', { required: true }),
    ],
    commercialDocument: {
      label: 'Grant Agreement Schedule',
      plural: 'Grant Agreement Schedules',
      prefix: 'GA',
      pricingModels: ['Fixed Grant', 'Cost Reimbursement', 'Milestone-based'],
      channelLabel: 'Programme',
      channelPlaceholder: 'e.g. Community health programme',
    },
    aiReviewFocus: ['use of funds and reporting', 'sanctions and counter-terrorism financing', 'safeguarding', 'audit rights'],
    newsTopic: 'nonprofit governance and grant regulation',
  },
];
