/**
 * Simplified Chinese for the country and industry pack texts, keyed by their English text.
 * `localize()` falls back to this when a LocalizedText has no `zh`; a pack text without an
 * entry here shows in English (tests/i18n.test.ts checks every pack text has one).
 */
export const PACK_ZH: Record<string, string> = {
  'Certificate of incorporation / registration': '公司注册证书',
  'Tax registration certificate': '税务登记证',
  'Singapore Law': '新加坡法律',
  'SIAC Arbitration, Singapore': '新加坡国际仲裁中心（SIAC）仲裁，新加坡',
  'Deed of establishment & amendments (Akta Pendirian)': '公司设立契据及修订（Akta Pendirian）',
  'Business identification number (NIB) & business licence': '营业识别号（NIB）及营业执照',
  'Tax registration (NPWP)': '税务登记（NPWP）',
  'Directors & PIC identity cards (KTP)': '董事及负责人身份证（KTP）',
  'Certificate of Residence (COR) for tax treaty': '税收协定居民身份证明（COR）',
  'DGT form for treaty withholding relief': '协定预提税优惠 DGT 表格',
  'Indonesian Law': '印度尼西亚法律',
  'BANI Arbitration, Jakarta': '印尼国家仲裁委员会（BANI）仲裁，雅加达',
  'executed in two originals bearing sufficient stamp duty (meterai)': '一式两份正本签署，并贴足印花税（meterai）',
  'ACRA BizFile business profile': 'ACRA BizFile 企业概况',
  'GST registration certificate': '消费税（GST）登记证',
  'SSM company profile / certificate of incorporation': 'SSM 公司概况 / 公司注册证书',
  'SST registration certificate': '销售与服务税（SST）登记证',
  'Malaysian Law': '马来西亚法律',
  'AIAC Arbitration, Kuala Lumpur': '亚洲国际仲裁中心（AIAC）仲裁，吉隆坡',
  'DBD company affidavit (certificate of registration)': 'DBD 公司宣誓书（注册证书）',
  'VAT registration certificate (Por Por 20)': '增值税登记证（Por Por 20）',
  'Thai Law': '泰国法律',
  'THAC Arbitration, Bangkok': '泰国仲裁中心（THAC）仲裁，曼谷',
  'Enterprise Registration Certificate (ERC)': '企业登记证（ERC）',
  'Investment Registration Certificate (foreign-invested entities)': '投资登记证（外商投资企业）',
  'Vietnamese Law': '越南法律',
  'VIAC Arbitration, Vietnam': '越南国际仲裁中心（VIAC）仲裁，越南',
  'SEC certificate of incorporation': 'SEC 公司注册证书',
  'BIR Certificate of Registration (Form 2303)': 'BIR 登记证（2303 表）',
  'Mayor\'s / business permit': '市长许可 / 营业许可',
  'Philippine Law': '菲律宾法律',
  'PDRCI Arbitration, Manila': '菲律宾争议解决中心（PDRCI）仲裁，马尼拉',
  'Certificate of incorporation (MCA)': '公司注册证书（MCA）',
  'PAN card copy': 'PAN 卡复印件',
  'Udyam (MSME) registration, if applicable': 'Udyam（中小微企业）登记（如适用）',
  'Indian Law': '印度法律',
  'MCIA Arbitration, Mumbai': '孟买国际仲裁中心（MCIA）仲裁，孟买',
  'Certificate of registered matters (Tokibo Tohon)': '登记事项证明书（登记簿誊本）',
  'Qualified invoice issuer registration notice': '合格发票开具人登记通知',
  'Japanese Law': '日本法律',
  'JCAA Arbitration, Tokyo': '日本商事仲裁协会（JCAA）仲裁，东京',
  'Business registration certificate': '营业登记证',
  'Corporate registry certificate': '法人登记簿证明',
  'Korean Law': '韩国法律',
  'KCAB International, Seoul': '大韩商事仲裁院国际仲裁中心（KCAB International），首尔',
  'Business licence (Yingye Zhizhao)': '营业执照',
  'PRC Law': '中华人民共和国法律',
  'CIETAC Arbitration, China': '中国国际经济贸易仲裁委员会（CIETAC）仲裁，中国',
  'Business Registration Certificate': '商业登记证',
  'Certificate of incorporation': '公司注册证书',
  'Hong Kong Law': '香港法律',
  'HKIAC Arbitration, Hong Kong': '香港国际仲裁中心（HKIAC）仲裁，香港',
  'Trade licence': '营业执照',
  'VAT registration certificate': '增值税登记证',
  'UAE Law': '阿联酋法律',
  'DIAC Arbitration, Dubai': '迪拜国际仲裁中心（DIAC）仲裁，迪拜',
  'Non-Disclosure Agreement (NDA)': '保密协议（NDA）',
  'Vendor assessment form': '供应商评估表',
  'Beneficial ownership declaration': '受益所有人声明',
  'Bank account confirmation letter': '银行账户确认函',
  'Termination notice': '终止通知',
  'Peer-to-Peer Lending': 'P2P 网络借贷',
  'Lender–platform agreement': '出借人与平台协议',
  'Borrower loan agreement': '借款人借款协议',
  'Channeling / co-lending agreement': '助贷 / 联合贷款协议',
  'Collection agency agreement': '催收机构协议',
  'Credit scoring / data provider agreement': '信用评分 / 数据提供方协议',
  'Escrow / virtual account agreement': '托管 / 虚拟账户协议',
  'AML/CFT & sanctions questionnaire': '反洗钱 / 反恐融资及制裁问卷',
  'Debt collector certification & collection code of conduct': '催收人员资质证书及催收行为准则',
  'Source-of-funds declaration (institutional lenders)': '资金来源声明（机构出借人）',
  'Material outsourcing / third-party risk assessment': '重大外包 / 第三方风险评估',
  'Information security certification (e.g. ISO 27001, PCI DSS)': '信息安全认证（如 ISO 27001、PCI DSS）',
  'Business continuity & disaster recovery plan': '业务连续性与灾难恢复计划',
  'Interest, fees & total cost cap': '利息、费用及总成本上限',
  'Flag if the total borrower cost (interest, fees and penalties) is not capped at the applicable regulatory maximum or is not disclosed as an annualised rate.': '如借款人总成本（利息、费用和罚金）未设在适用的监管上限内，或未以年化利率披露，则标记。',
  'Collection conduct': '催收行为',
  'Flag if collectors may use threats, contact non-guarantor third parties, collect outside permitted hours, or are not bound to the regulator’s collection code of conduct.': '如催收人员可能使用威胁、联系非担保第三方、在允许时间外催收，或不受监管机构催收行为准则约束，则标记。',
  'Borrower data access': '借款人数据访问',
  'Flag if the counterparty may access phone contacts, media or location data, or reuse borrower data beyond the stated purpose.': '如相对方可访问通讯录、媒体或位置数据，或超出所述目的使用借款人数据，则标记。',
  'Risk sharing & recourse': '风险分担与追索',
  'Flag if default risk, buyback obligations or first-loss cover is shifted to the platform without a cap.': '如违约风险、回购义务或首损补偿无上限地转嫁给平台，则标记。',
  'Escrow segregation': '托管资金隔离',
  'Flag if lender and borrower funds are not held in an escrow or virtual account segregated from the platform’s own funds.': '如出借人和借款人资金未存放于与平台自有资金隔离的托管或虚拟账户，则标记。',
  'Regulator audit access': '监管审计权',
  'Flag if the regulator and the platform cannot audit and inspect the outsourced service and its records.': '如监管机构和平台无法审计和检查外包服务及其记录，则标记。',
  'Withholding tax on interest paid to lenders; rates differ for domestic and foreign lenders, and treaty relief needs a certificate of residence.': '向出借人支付利息需缴纳预提税；境内外出借人税率不同，享受协定优惠需提供居民身份证明。',
  'Interest is usually exempt from VAT while platform, service and collection fees usually are not.': '利息通常免征增值税，而平台费、服务费和催收费通常需缴纳。',
  'Payment Gateway': '支付网关',
  'Merchant services agreement': '商户服务协议',
  'Acquiring bank partnership agreement': '收单银行合作协议',
  'Payment facilitator / sub-merchant agreement': '支付服务商 / 子商户协议',
  'Settlement & escrow agreement': '结算与托管协议',
  'Card scheme / e-wallet integration agreement': '卡组织 / 电子钱包接入协议',
  'Chargeback & dispute handling SLA': '拒付与争议处理 SLA',
  'PCI DSS attestation of compliance (AOC)': 'PCI DSS 合规证明（AOC）',
  'Merchant KYB & business activity verification': '商户 KYB 及经营活动核验',
  'Payment service licence / registration': '支付服务许可证 / 登记',
  'Settlement timing': '结算时间',
  'Flag if the settlement period is not fixed (e.g. T+1 / T+2) or funds can be held without a stated reserve policy.': '如结算周期不固定（如 T+1 / T+2），或可在无明确准备金政策的情况下冻结资金，则标记。',
  'Rolling reserve & holdback': '滚动准备金与保留款',
  'Flag if reserves can be imposed or increased unilaterally without a cap or release date.': '如可单方面设立或提高准备金且无上限或释放日期，则标记。',
  'Chargeback & scheme fines': '拒付与卡组织罚款',
  'Flag if chargebacks, fraud losses and scheme fines are allocated without evidence requirements or dispute timelines.': '如拒付、欺诈损失和卡组织罚款的分担没有证据要求或争议时限，则标记。',
  'MDR & fee changes': '商户手续费（MDR）及费用变更',
  'Flag if MDR or fees can change with less than 30 days’ notice or without a right to terminate.': '如 MDR 或费用可在少于 30 天通知的情况下变更，或无终止权，则标记。',
  'Card data handling': '卡数据处理',
  'Flag if a party that stores, processes or transmits card data is not bound to stay PCI DSS compliant and report breaches.': '如存储、处理或传输卡数据的一方无义务持续符合 PCI DSS 并报告泄露事件，则标记。',
  'Prohibited merchant categories': '禁止的商户类别',
  'Flag if there is no list of prohibited or high-risk businesses and no right to suspend non-compliant merchants.': '如没有禁止或高风险业务清单，也没有暂停违规商户的权利，则标记。',
  'VAT is usually due on MDR and service fees.': 'MDR 和服务费通常需缴纳增值税。',
  'Withholding tax may apply to fees paid to foreign card schemes and processors; treaty relief needs a certificate of residence.': '支付给境外卡组织和处理商的费用可能需缴纳预提税；享受协定优惠需提供居民身份证明。',
  'Banking & Investment': '银行与投资',
  'IT / core banking outsourcing agreement': 'IT / 核心银行系统外包协议',
  'Custody agreement': '托管协议',
  'Investment management / advisory agreement': '投资管理 / 顾问协议',
  'Selling agent / distribution agreement': '销售代理 / 分销协议',
  'ISDA / master trading agreement': 'ISDA / 主交易协议',
  'Non-disclosure agreement': '保密协议',
  'Financial services licence (bank, broker, fund manager)': '金融服务许可证（银行、经纪商、基金管理人）',
  'Regulator audit & inspection rights': '监管审计与检查权',
  'Flag if the regulator and the institution cannot audit, inspect and obtain records from the provider and its sub-contractors.': '如监管机构和机构无法审计、检查服务提供方及其分包商并获取记录，则标记。',
  'Sub-outsourcing & offshore processing': '转外包与境外处理',
  'Flag if sub-outsourcing or offshore data processing is allowed without prior written consent.': '如未经事先书面同意即可转外包或在境外处理数据，则标记。',
  'Business continuity & exit': '业务连续性与退出',
  'Flag if RTO/RPO, BCP testing or an exit plan with data return is missing.': '如缺少 RTO/RPO、BCP 测试或包含数据返还的退出计划，则标记。',
  'Customer secrecy': '客户保密',
  'Flag if bank-secrecy and customer confidentiality obligations do not survive termination.': '如银行保密和客户保密义务在终止后不再有效，则标记。',
  'Operational loss liability': '运营损失责任',
  'Flag if the provider’s liability for operational losses or data breaches is capped below 12 months’ fees.': '如服务提供方对运营损失或数据泄露的责任上限低于 12 个月费用，则标记。',
  'Best execution & conflicts': '最佳执行与利益冲突',
  'For brokerage or investment services, flag if best-execution and conflict-of-interest duties are absent.': '对于经纪或投资服务，如缺少最佳执行和利益冲突义务，则标记。',
  'Withholding tax on interest, dividends and service fees paid to non-residents; treaty relief needs a certificate of residence.': '向非居民支付利息、股息和服务费需缴纳预提税；享受协定优惠需提供居民身份证明。',
  'Counterparties may need FATCA / CRS self-certification.': '相对方可能需要提供 FATCA / CRS 自我证明。',
  'Enterprise B2B SaaS': '企业 B2B SaaS',
  'Master subscription agreement': '主订阅协议',
  'Order form': '订单表',
  'Data processing agreement': '数据处理协议',
  'Service level agreement': '服务水平协议',
  'Reseller / partner agreement': '经销商 / 合作伙伴协议',
  'Data Processing Agreement (DPA)': '数据处理协议（DPA）',
  'Security questionnaire (e.g. CAIQ, SIG Lite)': '安全问卷（如 CAIQ、SIG Lite）',
  'SOC 2 report or ISO 27001 certificate': 'SOC 2 报告或 ISO 27001 证书',
  'Sub-processor list': '子处理者清单',
  'Latest penetration test summary': '最新渗透测试摘要',
  'Uptime SLA & service credits': '可用性 SLA 与服务抵扣',
  'Flag if availability is below 99.5% or service credits are the sole remedy with no termination right for chronic failure.': '如可用性低于 99.5%，或服务抵扣是唯一救济且长期故障时无终止权，则标记。',
  'Auto-renewal & price increases': '自动续约与涨价',
  'Flag if the subscription renews automatically with less than 30 days’ opt-out notice or price increases are uncapped.': '如订阅自动续约且退出通知期少于 30 天，或涨价无上限，则标记。',
  'Data ownership, export & deletion': '数据所有权、导出与删除',
  'Flag if customer data ownership, export format or deletion timeline on termination is not stated.': '如未说明客户数据所有权、导出格式或终止后的删除时限，则标记。',
  'Security incident notification': '安全事件通知',
  'Flag if breach notification may take longer than 72 hours or lacks cooperation duties.': '如数据泄露通知可能超过 72 小时，或缺少配合义务，则标记。',
  'Liability cap carve-outs': '责任上限的例外',
  'Flag if the cap covers data breaches, confidentiality and IP indemnity, or is below 12 months’ fees.': '如责任上限涵盖数据泄露、保密和知识产权赔偿，或低于 12 个月费用，则标记。',
  'Sub-processor changes': '子处理者变更',
  'Flag if new sub-processors can be added without notice and an objection right.': '如可在未通知且无异议权的情况下新增子处理者，则标记。',
  'VAT / GST on digital services, including reverse charge on cross-border subscriptions.': '数字服务的增值税 / GST，包括跨境订阅的反向征收。',
  'Payments to foreign vendors may be treated as royalties or services for withholding tax.': '向境外供应商付款可能被视为特许权使用费或服务费以计算预提税。',
  'IT & Development': 'IT 与开发',
  'Software development agreement': '软件开发协议',
  'Statement of work': '工作说明书',
  'IT outsourcing / managed services agreement': 'IT 外包 / 托管服务协议',
  'Maintenance & support agreement': '维护与支持协议',
  'Source code escrow agreement': '源代码托管协议',
  'Personnel confidentiality & IP assignment undertakings': '人员保密及知识产权转让承诺书',
  'Secure development practices (SDLC, code review)': '安全开发实践（SDLC、代码审查）',
  'Professional indemnity insurance': '职业责任保险',
  'IP ownership & assignment': '知识产权归属与转让',
  'Flag if deliverables and source code are not assigned to the client on payment, or licence terms for pre-existing IP are unclear.': '如交付成果和源代码未在付款后转让给客户，或既有知识产权的许可条款不明确，则标记。',
  'Acceptance testing': '验收测试',
  'Flag if there are no acceptance criteria, testing period or limits on deemed acceptance.': '如没有验收标准、测试期或视为验收的限制，则标记。',
  'Change control': '变更控制',
  'Flag if scope changes can be billed without a signed change request.': '如范围变更可在没有签署变更申请的情况下计费，则标记。',
  'Defect warranty': '缺陷保修',
  'Flag if the defect warranty is shorter than 90 days or excludes critical bugs.': '如缺陷保修期短于 90 天或排除严重缺陷，则标记。',
  'Open-source components': '开源组件',
  'Flag if copyleft open-source software can be included without disclosure and approval.': '如可在未披露和批准的情况下包含 copyleft 开源软件，则标记。',
  'Key personnel & non-solicitation': '关键人员与禁止招揽',
  'Flag if key personnel can be replaced without consent or non-solicitation binds only one party.': '如关键人员可未经同意被替换，或禁止招揽条款仅约束一方，则标记。',
  'Withholding tax on services or royalties; individual developers need a personal tax ID.': '服务费或特许权使用费需缴纳预提税；个人开发者需提供个人税号。',
  'VAT on imported services via reverse charge.': '进口服务通过反向征收缴纳增值税。',
  'Influencer & KOL': '网红与 KOL',
  'Influencer / KOL engagement agreement': '网红 / KOL 合作协议',
  'Campaign brief & deliverables schedule': '活动简报与交付计划',
  'Content licence / usage rights agreement': '内容许可 / 使用权协议',
  'Talent management agency agreement': '达人经纪机构协议',
  'Identity & tax ID of the talent': '达人身份证明及税号',
  'Audience & engagement report (fake-follower check)': '受众与互动报告（虚假粉丝核查）',
  'Agency authority letter to act for the talent': '机构代表达人的授权书',
  'Brand safety & ad-fraud policy': '品牌安全与广告欺诈政策',
  'Sponsorship disclosure': '赞助披露',
  'Flag if the talent is not required to label content as paid or sponsored under advertising rules and platform policy.': '如未要求达人按广告规则和平台政策将内容标注为付费或赞助内容，则标记。',
  'Content approval & takedown': '内容审批与下架',
  'Flag if the brand has no pre-approval right or the talent has no duty to take content down within 24 hours on request.': '如品牌方没有事先审批权，或达人无义务在收到要求后 24 小时内下架内容，则标记。',
  'Usage rights & duration': '使用权与期限',
  'Flag if usage rights (channels, paid amplification, territory, duration) are unlimited or unspecified.': '如使用权（渠道、付费推广、地域、期限）无限制或未说明，则标记。',
  'Morality clause': '道德条款',
  'Flag if there is no termination and refund right for reputational misconduct.': '如因声誉不当行为没有终止和退款权，则标记。',
  'Category exclusivity': '品类排他',
  'Flag if competitor exclusivity has no category or time limit.': '如竞品排他没有品类或时间限制，则标记。',
  'Payment against proof': '凭证付款',
  'Flag if full payment is due before proof of posting and a performance report.': '如须在发布证明和效果报告之前支付全款，则标记。',
  'Withholding tax on payments to individual creators (non-employee income); rates differ with and without a tax ID.': '向个人创作者付款需缴纳预提税（非雇佣所得）；有无税号的税率不同。',
  'VAT applies when the creator or agency is VAT-registered; treaty relief for foreign creators needs a certificate of residence.': '创作者或机构登记为增值税纳税人时需缴纳增值税；境外创作者享受协定优惠需提供居民身份证明。',
  'Media & Creative': '媒体与创意',
  'Insertion order / media buying agreement': '投放订单 / 媒介购买协议',
  'Production services agreement': '制作服务协议',
  'Content licensing agreement': '内容许可协议',
  'Talent & model release': '达人与模特授权书',
  'Broadcast / publishing agreement': '广播 / 出版协议',
  'Placement documentation': '投放文件',
  'Music, footage & talent rights clearances': '音乐、素材及达人权利清算',
  'Delivery & make-good': '交付与补量',
  'Flag if under-delivery has no make-good or pro-rata refund.': '如投放不足时没有补量或按比例退款，则标记。',
  'Rights clearance warranty': '权利清算保证',
  'Flag if the supplier does not warrant music, footage and talent clearances and indemnify against infringement.': '如供应商不保证音乐、素材和达人权利已清算，也不承担侵权赔偿，则标记。',
  'Content standards': '内容标准',
  'Flag if there is no obligation to comply with advertising and broadcast content rules.': '如没有遵守广告和广播内容规则的义务，则标记。',
  'Measurement & verification': '监测与核验',
  'Flag if delivery is not measured by an agreed third-party tool (viewability, invalid traffic).': '如交付未通过约定的第三方工具（可见度、无效流量）衡量，则标记。',
  'IP in creatives': '创意作品的知识产权',
  'Flag if ownership or licence of final creatives and raw footage is unclear.': '如最终创意作品和原始素材的所有权或许可不明确，则标记。',
  'Payments may be royalties or services for withholding tax, which changes the rate.': '付款可能被视为特许权使用费或服务费以计算预提税，从而影响税率。',
  'VAT on advertising services and on foreign digital platforms.': '广告服务及境外数字平台的增值税。',
  'Hospitals & Medical': '医院与医疗',
  'Medical equipment supply & maintenance agreement': '医疗设备供应与维护协议',
  'Pharmaceutical supply agreement': '药品供应协议',
  'Doctor / specialist services agreement': '医生 / 专科医生服务协议',
  'Insurance / payer cooperation agreement': '保险 / 支付方合作协议',
  'Laboratory & referral agreement': '检验与转诊协议',
  'Medical waste management agreement': '医疗废物管理协议',
  'Healthcare facility / product licence': '医疗机构 / 产品许可证',
  'Practising licence of medical professionals': '医务人员执业许可证',
  'GxP / quality certification (e.g. ISO 13485, GMP)': 'GxP / 质量认证（如 ISO 13485、GMP）',
  'Professional liability insurance': '职业责任保险',
  'Medical / hazardous waste handling permit': '医疗 / 危险废物处理许可证',
  'Licences & credentials': '许可证与资质',
  'Flag if the counterparty does not warrant valid licences, product registrations and practising permits for the whole term.': '如相对方不保证在整个期限内持有有效的许可证、产品注册和执业许可，则标记。',
  'Patient data confidentiality': '患者数据保密',
  'Flag if medical records may be disclosed or processed beyond the stated purpose.': '如病历可能被披露或超出所述目的处理，则标记。',
  'Recalls & adverse events': '召回与不良事件',
  'Flag if there is no recall cooperation or adverse-event reporting duty.': '如没有召回配合或不良事件报告义务，则标记。',
  'Equipment uptime & maintenance': '设备可用性与维护',
  'Flag if critical equipment has no response time or uptime commitment.': '如关键设备没有响应时间或可用性承诺，则标记。',
  'Malpractice & product liability': '医疗过失与产品责任',
  'Flag if malpractice or product liability is not covered by insurance and indemnity.': '如医疗过失或产品责任未被保险和赔偿覆盖，则标记。',
  'Medical services are often VAT-exempt while equipment, supplies and non-medical services are not.': '医疗服务通常免征增值税，而设备、耗材和非医疗服务则不免征。',
  'Withholding tax on doctors’ professional fees.': '医生专业服务费需缴纳预提税。',
  'Healthtech & Telemedicine': '健康科技与远程医疗',
  'Telemedicine platform services agreement': '远程医疗平台服务协议',
  'Doctor / clinic partnership agreement': '医生 / 诊所合作协议',
  'Pharmacy fulfilment agreement': '药房履约协议',
  'Health data processing agreement': '健康数据处理协议',
  'Insurance / corporate wellness agreement': '保险 / 企业健康管理协议',
  'Telemedicine / digital health registration': '远程医疗 / 数字健康登记',
  'Health data protection agreement': '健康数据保护协议',
  'Pharmacy licence & pharmacist in charge': '药房许可证及执业药师',
  'Clinical responsibility': '临床责任',
  'Flag if diagnosis and prescribing are not the responsibility of licensed professionals.': '如诊断和开处方不由持证专业人员负责，则标记。',
  'Health data consent & localisation': '健康数据同意与本地化',
  'Flag if patient consent, data localisation or retention rules are not addressed.': '如未涉及患者同意、数据本地化或保存规则，则标记。',
  'Prescription & controlled drugs': '处方药与管制药品',
  'Flag if prescription or controlled drugs can be dispensed without a valid e-prescription.': '如处方药或管制药品可在没有有效电子处方的情况下发放，则标记。',
  'Availability & emergency referral': '可用性与紧急转诊',
  'Flag if there is no uptime commitment or emergency referral procedure.': '如没有可用性承诺或紧急转诊程序，则标记。',
  'Liability allocation': '责任分配',
  'Flag if the platform accepts unlimited clinical liability or fully disclaims platform failures.': '如平台承担无限临床责任，或完全免除平台故障责任，则标记。',
  'VAT on platform fees, while the medical consultation itself is often exempt.': '平台费需缴纳增值税，而医疗咨询本身通常免征。',
  'Withholding tax on fees paid to individual doctors.': '支付给个人医生的费用需缴纳预提税。',
  'Marketplace': '电商平台',
  'Merchant / seller agreement': '商户 / 卖家协议',
  'Platform terms of service': '平台服务条款',
  'Payment & escrow agreement': '支付与托管协议',
  'Logistics integration agreement': '物流对接协议',
  'Official store / brand partnership agreement': '官方旗舰店 / 品牌合作协议',
  'Merchant identity & business registration (KYB)': '商户身份及商业登记（KYB）',
  'Brand authorisation / distribution letter': '品牌授权 / 分销函',
  'Product safety & labelling compliance': '产品安全与标签合规',
  'IP & counterfeit takedown policy acknowledgement': '知识产权及假货下架政策确认书',
  'Commission & fee changes': '佣金与费用变更',
  'Flag if commissions or fees can change without at least 30 days’ notice.': '如佣金或费用可在少于 30 天通知的情况下变更，则标记。',
  'Counterfeit & prohibited goods': '假冒与违禁商品',
  'Flag if there is no takedown, delisting and indemnity for counterfeit or prohibited goods.': '如对假冒或违禁商品没有下架、除名和赔偿机制，则标记。',
  'Refunds & returns': '退款与退货',
  'Flag if refund and return responsibilities between platform and merchant are not allocated.': '如平台与商户之间的退款和退货责任未分配，则标记。',
  'Payout holdback': '结算款扣留',
  'Flag if payouts can be withheld without stated triggers and timelines.': '如结算款可在没有明确触发条件和时限的情况下被扣留，则标记。',
  'Data use & ranking': '数据使用与排名',
  'Flag if the use of merchant or customer data and paid visibility in rankings is not disclosed.': '如未披露商户或客户数据的使用方式及排名中的付费曝光，则标记。',
  'VAT on commissions and platform fees.': '佣金和平台费需缴纳增值税。',
  'The platform may have to collect or withhold tax on seller income.': '平台可能需要代收或代扣卖家收入的税款。',
  'Retail & Franchise': '零售与特许经营',
  'Franchise agreement': '特许经营协议',
  'Master franchise / area development agreement': '区域总特许 / 区域开发协议',
  'Trademark licence agreement': '商标许可协议',
  'Supply & distribution agreement': '供应与分销协议',
  'Store lease agreement': '店铺租赁协议',
  'Consignment agreement': '寄售协议',
  'Franchise registration / disclosure document': '特许经营登记 / 信息披露文件',
  'Trademark registration certificate': '商标注册证书',
  'Franchisee financial capacity statement': '加盟商财务能力说明',
  'Royalty & fees': '特许权使用费与费用',
  'Flag if royalty, marketing fund and initial fees lack a clear calculation basis.': '如特许权使用费、市场基金和初始费用缺乏明确的计算依据，则标记。',
  'Territory & encroachment': '区域与侵占',
  'Flag if the exclusive territory or encroachment protection is undefined.': '如独家区域或防侵占保护未定义，则标记。',
  'Tied supply & pricing': '指定采购与定价',
  'Flag if franchisees must buy from designated suppliers at prices set unilaterally (competition risk).': '如加盟商必须以单方确定的价格向指定供应商采购（竞争法风险），则标记。',
  'Brand standards & audits': '品牌标准与审计',
  'Flag if there are no operating standards, audit rights and cure periods.': '如没有经营标准、审计权和补救期，则标记。',
  'Renewal & post-term non-compete': '续约与期满后竞业禁止',
  'Flag if renewal conditions are missing or the non-compete exceeds a reasonable duration or area.': '如缺少续约条件，或竞业禁止超出合理期限或地域，则标记。',
  'Withholding tax on royalties; treaty relief for foreign franchisors.': '特许权使用费需缴纳预提税；境外特许人可享受协定优惠。',
  'VAT on franchise fees and goods.': '特许经营费和商品需缴纳增值税。',
  'Consumer & Omnichannel': '消费品与全渠道',
  'Distribution agreement': '分销协议',
  'Modern trade listing agreement': '现代渠道上架协议',
  'E-commerce official store agreement': '电商官方旗舰店协议',
  'Contract (toll) manufacturing agreement': '代工（来料加工）协议',
  'Trade promotion & merchandising agreement': '贸易促销与陈列协议',
  'Fulfilment agreement': '仓配履约协议',
  'Product registration / marketing authorisation (food, cosmetics)': '产品注册 / 上市许可（食品、化妆品）',
  'Halal certificate (where required)': '清真认证（如需要）',
  'Quality management certificate (e.g. ISO 9001, GMP)': '质量管理证书（如 ISO 9001、GMP）',
  'Listing fees & trading terms': '上架费与交易条款',
  'Flag if listing fees, rebates and payment terms are not fixed per channel.': '如上架费、返利和付款条件未按渠道固定，则标记。',
  'Minimum pricing': '最低定价',
  'Flag if minimum advertised or resale pricing rules may breach competition law.': '如最低广告价或转售价规则可能违反竞争法，则标记。',
  'Product recall': '产品召回',
  'Flag if recall costs and procedures are not allocated.': '如召回费用和程序未分配，则标记。',
  'Returns & expired goods': '退货与过期商品',
  'Flag if returns of expired or damaged goods have no cap or process.': '如过期或损坏商品的退货没有上限或流程，则标记。',
  'Channel exclusivity': '渠道排他',
  'Flag if exclusivity overlaps between distributors or channels.': '如经销商或渠道之间的排他权存在重叠，则标记。',
  'VAT on goods; withholding tax on promotion and service fees.': '商品需缴纳增值税；促销费和服务费需缴纳预提税。',
  'Excise may apply to some products (e.g. sweetened drinks, alcohol, tobacco).': '部分产品可能需缴纳消费税（如含糖饮料、酒类、烟草）。',
  'Legal & Consulting': '法律与咨询',
  'Engagement letter': '委托函',
  'Retainer agreement': '常年顾问协议',
  'Referral / co-counsel agreement': '转介 / 联合代理协议',
  'Conflict of interest declaration': '利益冲突声明',
  'Advocate / professional practising licence': '律师 / 专业执业许可证',
  'Client identification (KYC) for regulated professions': '受监管职业的客户身份识别（KYC）',
  'Scope & exclusions': '范围与除外',
  'Flag if the scope of advice and its exclusions are not written.': '如咨询范围及其除外事项未书面约定，则标记。',
  'Fee basis & caps': '收费依据与上限',
  'Flag if hourly rates, fee caps, disbursements and success fees are not defined.': '如小时费率、费用上限、代垫费用和成功费未定义，则标记。',
  'Conflicts of interest': '利益冲突',
  'Flag if there is no conflict-check warranty or disclosure duty.': '如没有利益冲突审查保证或披露义务，则标记。',
  'Confidentiality & privilege': '保密与特权',
  'Flag if handling of privileged material and survival of confidentiality are missing.': '如缺少特权资料的处理及保密义务的存续条款，则标记。',
  'Professional liability cap': '职业责任上限',
  'Flag if professional liability is capped below the fees paid or excludes negligence.': '如职业责任上限低于已付费用或排除过失责任，则标记。',
  'Withholding tax on professional fees; rates differ for individuals and firms.': '专业服务费需缴纳预提税；个人和机构税率不同。',
  'VAT on professional services.': '专业服务需缴纳增值税。',
  'Digital Agency': '数字代理',
  'Agency services agreement': '代理服务协议',
  'Statement of work / retainer scope': '工作说明书 / 常年服务范围',
  'Media buying insertion order': '媒介购买投放订单',
  'Ad platform reseller agreement': '广告平台代理协议',
  'Data processing agreement (tracking & audiences)': '数据处理协议（追踪与受众）',
  'Ad platform partner status / reseller authorisation': '广告平台合作伙伴资质 / 代理授权',
  'Media spend transparency': '媒介花费透明度',
  'Flag if media spend, agency markup and platform rebates are not disclosed separately.': '如媒介花费、代理加价和平台返点未分别披露，则标记。',
  'KPI & attribution': 'KPI 与归因',
  'Flag if KPIs are guaranteed without an attribution method or excluded factors.': '如保证 KPI 但没有归因方法或排除因素，则标记。',
  'Ad account & data ownership': '广告账户与数据所有权',
  'Flag if ad accounts, pixels and audience data belong to the agency instead of the client.': '如广告账户、像素和受众数据归代理而非客户所有，则标记。',
  'Creative IP': '创意知识产权',
  'Flag if creatives and source files are not transferred to the client on payment.': '如创意作品和源文件未在付款后转交客户，则标记。',
  'Tracking consent': '追踪同意',
  'Flag if the agency may deploy tracking without a consent mechanism.': '如代理可在没有同意机制的情况下部署追踪，则标记。',
  'VAT on agency fees; media pass-through may be taxed differently when invoiced separately.': '代理费需缴纳增值税；媒介代付款单独开票时税务处理可能不同。',
  'Withholding tax on payments to foreign ad platforms.': '向境外广告平台付款需缴纳预提税。',
  'Headhunting & Recruitment': '猎头与招聘',
  'Recruitment services agreement': '招聘服务协议',
  'Retained search agreement': '保留式猎头协议',
  'Job order (contingency)': '职位委托（成功收费）',
  'Staffing / outsourcing agreement': '人力派遣 / 外包协议',
  'Candidate data processing agreement': '候选人数据处理协议',
  'Private placement / outsourcing agency licence': '私营职业介绍 / 外包机构许可证',
  'Labour law compliance statement (wages, social security)': '劳动法合规声明（工资、社保）',
  'Background screening methodology & consent': '背景调查方法及同意书',
  'Fee & replacement guarantee': '费用与替换保证',
  'Flag if the placement fee basis or replacement guarantee (e.g. 90 days) is missing.': '如缺少推荐费计算依据或替换保证（如 90 天），则标记。',
  'Candidate ownership': '候选人归属',
  'Flag if the validity period of candidate introductions and double-introduction rules are undefined.': '如候选人推荐的有效期和重复推荐规则未定义，则标记。',
  'Non-solicitation': '禁止招揽',
  'Flag if non-solicitation of placed or outsourced staff is one-sided or unlimited in time.': '如对已安置或外包员工的禁止招揽条款是单方面的或无时间限制，则标记。',
  'Employment liability (outsourcing)': '用工责任（外包）',
  'Flag if wages, social security and severance for outsourced staff are not allocated.': '如外包员工的工资、社保和遣散费未分配，则标记。',
  'Candidate data': '候选人数据',
  'Flag if candidate consent and data retention are not addressed.': '如未涉及候选人同意和数据保存，则标记。',
  'Withholding tax and VAT on recruitment service fees.': '招聘服务费需缴纳预提税和增值税。',
  'For outsourced workers, the employer of record handles payroll tax and social security.': '对于外包人员，名义雇主负责工资税和社保。',
  'Freight Logistics': '货运物流',
  'Freight forwarding agreement': '货运代理协议',
  'Transport / carriage contract': '运输 / 承运合同',
  'Customs brokerage agreement': '报关代理协议',
  'Warehousing agreement': '仓储协议',
  'Transport / forwarding operating licence': '运输 / 货代经营许可证',
  'Cargo liability insurance': '货物责任保险',
  'Customs broker licence / AEO status': '报关行许可证 / AEO 资质',
  'Sanctions & dual-use export screening': '制裁与两用物项出口筛查',
  'Loss & damage liability limits': '灭失与损坏责任限额',
  'Flag if carrier liability limits are below the applicable convention or undisclosed.': '如承运人责任限额低于适用公约标准或未披露，则标记。',
  'Incoterms & transfer of risk': '国际贸易术语与风险转移',
  'Flag if the Incoterm and the point where risk transfers are not stated.': '如未说明适用的国际贸易术语及风险转移点，则标记。',
  'Customs duties & penalties': '关税与罚款',
  'Flag if responsibility for duties, penalties and misdeclaration is not allocated.': '如关税、罚款和错误申报的责任未分配，则标记。',
  'Demurrage & detention': '滞期费与滞箱费',
  'Flag if demurrage and detention charges have no free time or cap.': '如滞期费和滞箱费没有免费期或上限，则标记。',
  'Dangerous goods': '危险品',
  'Flag if dangerous goods declarations and handling duties are missing.': '如缺少危险品申报和处理义务，则标记。',
  'International freight may be zero-rated for VAT while domestic logistics is standard-rated.': '国际货运可能适用增值税零税率，而境内物流适用标准税率。',
  'Shipping and air transport treaty articles may exempt foreign carriers from withholding tax.': '海运和空运的税收协定条款可能免除境外承运人的预提税。',
  'Cold Chain Storage': '冷链仓储',
  'Cold storage / warehousing agreement': '冷库 / 仓储协议',
  'Temperature-controlled transport agreement': '温控运输协议',
  'Temperature monitoring & IoT services agreement': '温度监测与物联网服务协议',
  'Reefer / chiller lease & maintenance agreement': '冷藏柜 / 冷机租赁与维护协议',
  'Good distribution / storage practice certificate (food or pharma)': '良好分销 / 储存规范证书（食品或药品）',
  'Temperature mapping & validation report': '温度分布与验证报告',
  'HACCP / ISO 22000 certificate': 'HACCP / ISO 22000 证书',
  'Cargo / stock liability insurance': '货物 / 库存责任保险',
  'Temperature excursion liability': '温度偏离责任',
  'Flag if liability for product loss from temperature excursions is excluded or capped below the value of the goods.': '如因温度偏离导致的产品损失责任被排除或上限低于货值，则标记。',
  'Monitoring & data logs': '监测与数据记录',
  'Flag if continuous temperature logging, alarms and data access are not required.': '如未要求连续温度记录、报警和数据访问，则标记。',
  'Backup power & contingency': '备用电源与应急预案',
  'Flag if backup power and contingency storage are not guaranteed.': '如未保证备用电源和应急存储，则标记。',
  'Stock count & shrinkage': '盘点与损耗',
  'Flag if the stock reconciliation frequency and shrinkage tolerance are missing.': '如缺少库存对账频率和损耗容忍度，则标记。',
  'Product segregation': '产品隔离',
  'Flag if segregation of food, pharmaceutical and halal goods is not required.': '如未要求隔离食品、药品和清真商品，则标记。',
  'VAT and withholding tax on storage and handling services.': '仓储及装卸服务需缴纳增值税和预提税。',
  'Delivery & Fleet': '配送与车队',
  'Last-mile delivery agreement': '最后一公里配送协议',
  'Courier services agreement': '快递服务协议',
  'Fleet rental / leasing agreement': '车队租赁 / 融资租赁协议',
  'Driver partnership agreement': '司机合作协议',
  'Vehicle maintenance agreement': '车辆维护协议',
  'Transport / courier operating licence': '运输 / 快递经营许可证',
  'Vehicle registration & roadworthiness certificates': '车辆登记及适路证书',
  'Driver licences & background checks': '驾驶执照及背景调查',
  'Vehicle, third-party & goods-in-transit insurance': '车辆险、第三者责任险及在途货物险',
  'Delivery SLA & proof of delivery': '配送 SLA 与签收证明',
  'Flag if the delivery SLA, proof of delivery and failed-delivery rules are missing.': '如缺少配送 SLA、签收证明和配送失败规则，则标记。',
  'Loss, damage & COD remittance': '灭失、损坏与货到付款回款',
  'Flag if liability for lost or damaged parcels and cash-on-delivery remittance timelines are not set.': '如未约定包裹灭失或损坏的责任及货到付款回款时限，则标记。',
  'Driver status': '司机身份',
  'Flag if control or exclusivity in the partnership model creates employment liability.': '如合作模式中的控制或排他性可能产生劳动雇佣责任，则标记。',
  'Accidents & traffic fines': '事故与交通罚款',
  'Flag if maintenance, accident and traffic-fine responsibility is not allocated.': '如维护、事故和交通罚款责任未分配，则标记。',
  'Recipient data use': '收件人数据使用',
  'Flag if recipient data may be reused beyond delivery.': '如收件人数据可能在配送之外被再次使用，则标记。',
  'VAT on delivery services.': '配送服务需缴纳增值税。',
  'Withholding tax on payments to individual driver partners.': '向个人司机合作伙伴付款需缴纳预提税。',
  'Public Transportation': '公共交通',
  'Concession / public service obligation agreement': '特许经营 / 公共服务义务协议',
  'Rolling stock / bus supply & maintenance agreement': '机车车辆 / 公交车供应与维护协议',
  'Ticketing & fare collection agreement': '票务与收费协议',
  'Operations & maintenance agreement': '运营与维护协议',
  'Station advertising / retail concession': '车站广告 / 商业特许经营',
  'Transport operating licence / route permit': '运输经营许可证 / 线路许可',
  'Safety management system certification': '安全管理体系认证',
  'Vehicle type approval & roadworthiness': '车辆型式认证与适路性',
  'Passenger liability insurance': '乘客责任保险',
  'Service KPIs & penalties': '服务 KPI 与罚则',
  'Flag if headway, punctuality and availability KPIs have no penalty or bonus mechanism.': '如发车间隔、准点率和可用性 KPI 没有罚款或奖励机制，则标记。',
  'Fare & subsidy adjustment': '票价与补贴调整',
  'Flag if the fare or public service subsidy adjustment formula is undefined.': '如票价或公共服务补贴调整公式未定义，则标记。',
  'Safety & incident reporting': '安全与事故报告',
  'Flag if safety obligations and incident reporting timelines are missing.': '如缺少安全义务和事故报告时限，则标记。',
  'Asset handback': '资产移交',
  'Flag if the required condition of assets at the end of the concession is not specified.': '如未规定特许期结束时资产应达到的状态，则标记。',
  'Step-in rights': '介入权',
  'Flag if the authority has no step-in right when service fails.': '如服务失败时主管部门没有介入权，则标记。',
  'Public transport fares are often VAT-exempt; supply and O&M contracts are not.': '公共交通票价通常免征增值税；供应及运维合同则不免征。',
  'Renewable Energy': '可再生能源',
  'Power purchase agreement (PPA)': '购电协议（PPA）',
  'EPC contract': 'EPC 总承包合同',
  'Land / rooftop lease agreement': '土地 / 屋顶租赁协议',
  'Equipment supply agreement (modules, turbines, batteries)': '设备供应协议（组件、风机、电池）',
  'Renewable energy certificate (REC) agreement': '绿证（REC）协议',
  'HSE management system certificate (e.g. ISO 45001, ISO 14001)': 'HSE 管理体系证书（如 ISO 45001、ISO 14001）',
  'Operating permits and concessions': '运营许可与特许权',
  'Equipment certification (IEC 61215/61730, IEC 61400)': '设备认证（IEC 61215/61730、IEC 61400）',
  'Grid connection approval': '并网批复',
  'Environmental impact assessment approval': '环境影响评价批复',
  'Tariff & indexation': '电价与指数调整',
  'Flag if the tariff, escalation and currency indexation are not defined.': '如电价、价格递增和货币指数调整未定义，则标记。',
  'Take-or-pay & curtailment': '照付不议与限电',
  'Flag if there is no deemed-energy or curtailment compensation.': '如没有视同发电量或限电补偿，则标记。',
  'Performance guarantees': '性能保证',
  'Flag if performance ratio or availability guarantees and liquidated damages are missing.': '如缺少性能比或可用率保证及违约赔偿金，则标记。',
  'Change in law & grid unavailability': '法律变更与电网不可用',
  'Flag if change-in-law relief or grid unavailability risk is not allocated.': '如法律变更救济或电网不可用风险未分配，则标记。',
  'Decommissioning': '退役',
  'Flag if decommissioning and site restoration obligations are missing.': '如缺少退役和场地恢复义务，则标记。',
  'Tax holidays and VAT or import-duty exemptions on equipment usually carry conditions that the contract should support.': '免税期以及设备的增值税或进口关税减免通常附带条件，合同应予以支持。',
  'Oil & Gas': '石油与天然气',
  'Production sharing contract / concession': '产品分成合同 / 特许权',
  'Joint operating agreement (JOA)': '联合作业协议（JOA）',
  'Master services / call-off contract': '主服务 / 框架调用合同',
  'Drilling services contract': '钻井服务合同',
  'Vessel charter party': '船舶租约',
  'Gas sales / offtake agreement': '天然气销售 / 包销协议',
  'Vendor registration with the operator / regulator': '在作业者 / 监管机构处的供应商登记',
  'Local content certification': '本地成分认证',
  'Well control, pollution & P&I insurance': '井控、污染及保赔保险',
  'Knock-for-knock indemnities': '对等互免赔偿（knock-for-knock）',
  'Flag if mutual indemnities for each party’s personnel and property are missing or asymmetric.': '如缺少各方人员和财产的相互赔偿条款或条款不对等，则标记。',
  'Pollution & well control': '污染与井控',
  'Flag if pollution and blowout liability is not allocated and insured.': '如污染和井喷责任未分配且未投保，则标记。',
  'Consequential loss exclusion': '间接损失除外',
  'Flag if a mutual exclusion of consequential loss is missing.': '如缺少相互排除间接损失的条款，则标记。',
  'Day rates & liquidated damages': '日费率与违约赔偿金',
  'Flag if standby or downtime day rates and liquidated damages have no cap.': '如待命或停工日费率及违约赔偿金没有上限，则标记。',
  'Local content': '本地成分',
  'Flag if local content obligations and reporting are missing.': '如缺少本地成分义务和报告，则标记。',
  'Withholding tax on services by non-resident contractors, and permanent establishment risk for long projects.': '非居民承包商提供的服务需缴纳预提税，长期项目存在常设机构风险。',
  'Cost recovery rules under the PSC and import duty facilities.': '产品分成合同下的成本回收规则及进口关税便利。',
  'Water & Sanitation': '水务与卫生',
  'Water supply cooperation / concession agreement': '供水合作 / 特许经营协议',
  'Build-operate-transfer (BOT) agreement': '建设-运营-移交（BOT）协议',
  'Bulk water purchase agreement': '趸售水购买协议',
  'Wastewater treatment O&M agreement': '污水处理运维协议',
  'Chemical & equipment supply agreement': '化学品与设备供应协议',
  'Water abstraction / wastewater discharge permits': '取水 / 污水排放许可证',
  'Accredited water quality laboratory results': '认可水质实验室检测结果',
  'Water quality & volume': '水质与水量',
  'Flag if quality parameters and minimum supply volumes are not guaranteed.': '如水质参数和最低供水量未得到保证，则标记。',
  'Tariff adjustment': '水价调整',
  'Flag if the tariff or offtake price adjustment mechanism is missing.': '如缺少水价或采购价调整机制，则标记。',
  'Non-revenue water': '无收益水',
  'Flag if non-revenue water reduction targets and penalties are undefined.': '如无收益水降低目标及罚则未定义，则标记。',
  'Discharge compliance': '排放合规',
  'Flag if discharge limits and monitoring duties are not stated.': '如未说明排放限值和监测义务，则标记。',
  'Asset transfer': '资产移交',
  'Flag if the condition of assets at transfer (BOT) is not specified.': '如未规定移交（BOT）时资产的状态，则标记。',
  'Clean water supply is often VAT-exempt; construction and O&M services are not.': '清洁供水通常免征增值税；建设和运维服务则不免征。',
  'Education & Research': '教育与科研',
  'Institutional cooperation agreement / MoU': '机构合作协议 / 谅解备忘录',
  'Research collaboration agreement': '科研合作协议',
  'Sponsored research / grant agreement': '委托研究 / 资助协议',
  'Content / curriculum licensing agreement': '内容 / 课程许可协议',
  'Internship agreement': '实习协议',
  'Research data sharing agreement': '科研数据共享协议',
  'Accreditation / licence': '认证 / 许可证',
  'Child safeguarding policy': '儿童保护政策',
  'Research ethics committee approval': '科研伦理委员会批准',
  'Research data management & sharing plan': '科研数据管理与共享计划',
  'IP in research outputs': '科研成果的知识产权',
  'Flag if ownership of background and foreground IP and publication rights are unclear.': '如背景知识产权与新产生知识产权的归属及发表权不明确，则标记。',
  'Publication & confidentiality': '发表与保密',
  'Flag if the sponsor can block publication indefinitely.': '如资助方可无限期阻止发表，则标记。',
  'Human-subject ethics': '人体受试者伦理',
  'Flag if ethics approval and informed-consent obligations are missing.': '如缺少伦理批准和知情同意义务，则标记。',
  'Student & minor data': '学生与未成年人数据',
  'Flag if processing of student or minor data lacks consent and safeguards.': '如处理学生或未成年人数据缺乏同意和保护措施，则标记。',
  'Funding milestones & reporting': '资助里程碑与报告',
  'Flag if disbursement milestones and reporting duties are undefined.': '如拨款里程碑和报告义务未定义，则标记。',
  'Education services are often VAT-exempt.': '教育服务通常免征增值税。',
  'Withholding tax on honoraria paid to individual lecturers and researchers.': '支付给个人讲师和研究人员的酬金需缴纳预提税。',
  'Philanthropy & Donations': '慈善与捐赠',
  'Grant agreement': '资助协议',
  'Donation agreement': '捐赠协议',
  'Corporate CSR partnership agreement': '企业社会责任合作协议',
  'Fundraising platform agreement': '筹款平台协议',
  'Endowment / fund management agreement': '捐赠基金 / 资金管理协议',
  'Foundation / charity / NGO registration': '基金会 / 慈善机构 / 非政府组织登记',
  'Counter-terrorism financing & sanctions screening': '反恐融资与制裁筛查',
  'Public fundraising permit': '公开募捐许可',
  'Audited financial statements of the grantee': '受资助方经审计的财务报表',
  'Restricted use of funds': '资金限定用途',
  'Flag if purpose restrictions and prohibited uses of funds are not stated.': '如未说明资金的用途限制和禁止用途，则标记。',
  'Reporting & audit': '报告与审计',
  'Flag if narrative and financial reporting and audit rights are missing.': '如缺少叙述性与财务报告及审计权，则标记。',
  'Refund & clawback': '退款与追回',
  'Flag if unused or misused funds cannot be recovered.': '如未使用或被挪用的资金无法追回，则标记。',
  'Donor recognition': '捐赠方鸣谢',
  'Flag if use of the donor’s name or logo does not need approval.': '如使用捐赠方名称或标志无需批准，则标记。',
  'Beneficiary & sanctions screening': '受益人与制裁筛查',
  'Flag if screening of beneficiaries and sub-grantees against sanctions lists is not required.': '如未要求对受益人和次级受资助方进行制裁名单筛查，则标记。',
  'Donations may be tax-deductible only when the recipient qualifies; official donation receipts are needed.': '仅当受赠方符合条件时捐赠才可税前扣除；需要正式的捐赠收据。',
  'Grants received may be exempt from income tax for qualifying recipients.': '符合条件的受资助方所获资助可能免征所得税。',
  'NGO & Humanitarian': '非政府组织与人道主义',
  'Implementing partner agreement': '执行伙伴协议',
  'Sub-grant agreement': '次级资助协议',
  'Framework / long-term supply agreement': '框架 / 长期供应协议',
  'Memorandum of understanding with government': '与政府的谅解备忘录',
  'Beneficiary data sharing agreement': '受益人数据共享协议',
  'PSEA & safeguarding policy': '防范性剥削与性虐待（PSEA）及保护政策',
  'Procurement & anti-fraud policy': '采购与反欺诈政策',
  'Eligible costs & budget flexibility': '合格费用与预算灵活性',
  'Flag if eligible costs and budget reallocation limits are undefined.': '如合格费用和预算调整限额未定义，则标记。',
  'Safeguarding & PSEA': '保护与 PSEA',
  'Flag if safeguarding obligations and incident reporting are missing.': '如缺少保护义务和事件报告，则标记。',
  'Aid diversion & sanctions': '援助挪用与制裁',
  'Flag if aid-diversion prevention and sanctions screening are absent.': '如缺少防止援助挪用和制裁筛查的措施，则标记。',
  'Beneficiary data': '受益人数据',
  'Flag if beneficiary data protection and sharing restrictions are missing.': '如缺少受益人数据保护和共享限制，则标记。',
  'Donor flow-down': '捐赠方条款传递',
  'Flag if donor conditions are not flowed down to sub-grantees.': '如捐赠方条件未传递给次级受资助方，则标记。',
  'Tax and duty exemptions for humanitarian goods usually need prior approval.': '人道主义物资的税费减免通常需要事先批准。',
  'Office Procurement': '办公采购',
  'Framework supply agreement': '框架供应协议',
  'Purchase order terms & conditions': '采购订单条款与条件',
  'Facility management services agreement': '设施管理服务协议',
  'IT hardware & software licence procurement': 'IT 硬件与软件许可采购',
  'Cleaning / security services agreement': '保洁 / 安保服务协议',
  'Vendor registration & bank account verification': '供应商登记与银行账户核验',
  'Signed supplier code of conduct': '已签署的供应商行为准则',
  'Anti-bribery & conflict of interest declaration': '反贿赂与利益冲突声明',
  'Labour compliance of outsourced staff (wages, social security)': '外包人员的劳动合规（工资、社保）',
  'Price validity & escalation': '价格有效期与上调',
  'Flag if prices are not fixed for the term or escalation is uncapped.': '如价格在期限内不固定或上调无上限，则标记。',
  'Delivery & acceptance': '交付与验收',
  'Flag if delivery times and acceptance / rejection rights are missing.': '如缺少交付时间及验收 / 拒收权，则标记。',
  'Warranty & replacement': '保修与更换',
  'Flag if goods warranty and replacement timelines are missing.': '如缺少商品保修和更换时限，则标记。',
  'Outsourced staff liability': '外包人员责任',
  'Flag if wages and social security of service staff are not the vendor’s responsibility.': '如服务人员的工资和社保不由供应商负责，则标记。',
  'Anti-bribery': '反贿赂',
  'Flag if there is no anti-bribery clause with a termination right.': '如没有附带终止权的反贿赂条款，则标记。',
  'VAT on goods and services.': '商品和服务需缴纳增值税。',
  'Withholding tax on services such as cleaning, security and catering.': '保洁、安保和餐饮等服务需缴纳预提税。',
  'Property Rental': '物业租赁',
  'Lease agreement': '租赁协议',
  'Letter of intent / offer to lease': '意向书 / 租赁要约',
  'Service charge / building management agreement': '物业服务费 / 楼宇管理协议',
  'Fit-out agreement': '装修协议',
  'Property management agreement': '物业管理协议',
  'Proof of title / land certificate': '产权证明 / 土地证',
  'Landlord authority to lease (owner or power of attorney)': '出租人出租权限（业主或授权委托书）',
  'Building permit & certificate of occupancy': '建筑许可证及入住许可证',
  'Property & public liability insurance': '财产险与公众责任险',
  'Rent review & escalation': '租金调整与递增',
  'Flag if rent escalation is uncapped or the review mechanism is undefined.': '如租金递增无上限或调整机制未定义，则标记。',
  'Security deposit': '押金',
  'Flag if the deposit amount, holding and refund timeline are missing.': '如缺少押金金额、保管方式和退还时限，则标记。',
  'Early termination': '提前终止',
  'Flag if there is no break option or the penalty exceeds the remaining rent.': '如没有提前解约选择权，或违约金超过剩余租金，则标记。',
  'Repairs & maintenance': '维修与保养',
  'Flag if structural and non-structural repairs are not split between the parties.': '如结构性和非结构性维修未在双方之间划分，则标记。',
  'Reinstatement': '恢复原状',
  'Flag if reinstatement obligations at lease end are undefined.': '如租期结束时的恢复原状义务未定义，则标记。',
  'Withholding / final tax on rental income, usually withheld by the tenant.': '租金收入的预提税 / 最终税，通常由承租人代扣。',
  'VAT on commercial rent and service charges; stamp duty on the lease.': '商业租金和物业服务费需缴纳增值税；租赁合同需缴纳印花税。',
  'Freelance Workforce': '自由职业人员',
  'Independent contractor agreement': '独立承包商协议',
  'Confidentiality & IP assignment agreement': '保密及知识产权转让协议',
  'Freelance platform terms': '自由职业平台条款',
  'Employer-of-record agreement': '名义雇主（EOR）协议',
  'Identity document & personal tax ID': '身份证件及个人税号',
  'Bank account ownership verification': '银行账户归属核验',
  'Confidentiality & IP assignment undertaking': '保密及知识产权转让承诺书',
  'Worker classification assessment (contractor vs employee)': '用工性质评估（承包商或雇员）',
  'Contractor classification': '承包商定性',
  'Flag if control, exclusivity, fixed hours or employee-like benefits create a risk of reclassification as employment.': '如控制、排他、固定工时或类似雇员的福利可能导致被认定为雇佣关系，则标记。',
  'IP assignment': '知识产权转让',
  'Flag if work product and IP are not assigned on payment.': '如工作成果和知识产权未在付款后转让，则标记。',
  'Payment terms': '付款条件',
  'Flag if payment is not due within a fixed period after the deliverable is accepted.': '如付款未在交付成果验收后的固定期限内到期，则标记。',
  'Confidentiality & system access': '保密与系统访问',
  'Flag if access to company systems or data lacks confidentiality and return obligations.': '如访问公司系统或数据缺乏保密和归还义务，则标记。',
  'Termination & completed work': '终止与已完成工作',
  'Flag if termination notice or payment for completed work is missing.': '如缺少终止通知或已完成工作的付款，则标记。',
  'Withholding tax on individual non-employee income.': '个人非雇佣所得需缴纳预提税。',
  'Social security duties arise if the engagement is reclassified as employment; treaty relief for foreign freelancers needs a certificate of residence.': '如被认定为雇佣关系，将产生社保义务；境外自由职业者享受协定优惠需提供居民身份证明。',
  'General': '通用',
  'Master services agreement': '主服务协议',
  'Supply agreement': '供应协议',
  'Partnership agreement / MoU': '合作协议 / 谅解备忘录',
  'Limitation of liability': '责任限制',
  'Flag if liability is uncapped for either party or the cap is below 12 months’ fees.': '如任一方责任无上限，或上限低于 12 个月费用，则标记。',
  'Termination & notice': '终止与通知',
  'Flag if there is no termination for convenience or the notice period is unclear.': '如没有任意终止权或通知期不明确，则标记。',
  'Confidentiality': '保密',
  'Flag if confidentiality has no survival period after termination.': '如保密义务在终止后没有存续期，则标记。',
  'Flag if payment terms, late-payment interest or invoicing requirements are missing.': '如缺少付款条件、逾期付款利息或开票要求，则标记。',
  'Dispute resolution': '争议解决',
  'Flag if governing law or the dispute forum is missing or differs from the organization default.': '如缺少适用法律或争议解决机构，或与组织默认值不同，则标记。',
  'VAT / GST on goods and services.': '商品和服务的增值税 / GST。',
  'Withholding tax on services and cross-border payments.': '服务费及跨境付款需缴纳预提税。',
};

/**
 * Indonesian and Chinese for plain-string pack fields shown in the UI (country names, identifier
 * labels, partner types, compliance standards), keyed by English. Stored values stay in English.
 */
export const PACK_NAMES: Record<string, { id: string; zh: string }> = {
  'International (jurisdiction-neutral)': { id: 'Internasional (netral yurisdiksi)', zh: '国际（不限司法辖区）' },
  'Tax identification number': { id: 'Nomor identifikasi pajak', zh: '纳税人识别号' },
  'Company registration number': { id: 'Nomor registrasi perusahaan', zh: '公司注册号' },
  'Legal Entity Identifier (LEI)': { id: 'Legal Entity Identifier (LEI)', zh: '法人机构识别编码（LEI）' },
  'Indonesia': { id: 'Indonesia', zh: '印度尼西亚' },
  'NPWP (Nomor Pokok Wajib Pajak)': { id: 'NPWP (Nomor Pokok Wajib Pajak)', zh: 'NPWP（纳税人识别号）' },
  'NIB (Nomor Induk Berusaha)': { id: 'NIB (Nomor Induk Berusaha)', zh: 'NIB（营业识别号）' },
  'Nomor SK Kemenkumham (AHU)': { id: 'Nomor SK Kemenkumham (AHU)', zh: '法律与人权部批准文号（AHU）' },
  'NIK (Nomor Induk Kependudukan)': { id: 'NIK (Nomor Induk Kependudukan)', zh: 'NIK（居民身份号码）' },
  'Singapore': { id: 'Singapura', zh: '新加坡' },
  'Unique Entity Number (UEN)': { id: 'Unique Entity Number (UEN)', zh: '唯一实体编号（UEN）' },
  'GST registration number': { id: 'Nomor registrasi GST', zh: 'GST 登记号' },
  'NRIC / FIN': { id: 'NRIC / FIN', zh: '身份证 / 外国人识别号（NRIC / FIN）' },
  'Malaysia': { id: 'Malaysia', zh: '马来西亚' },
  'SSM company registration number': { id: 'Nomor registrasi perusahaan SSM', zh: 'SSM 公司注册号' },
  'Tax Identification Number (TIN)': { id: 'Tax Identification Number (TIN)', zh: '纳税人识别号（TIN）' },
  'SST registration number': { id: 'Nomor registrasi SST', zh: 'SST 登记号' },
  'MyKad number': { id: 'Nomor MyKad', zh: 'MyKad 身份证号' },
  'Thailand': { id: 'Thailand', zh: '泰国' },
  '13-digit Tax ID / juristic person number': { id: 'Tax ID 13 digit / nomor badan hukum', zh: '13 位税号 / 法人编号' },
  'Thai citizen ID': { id: 'Nomor identitas warga Thailand', zh: '泰国公民身份证号' },
  'Vietnam': { id: 'Vietnam', zh: '越南' },
  'Enterprise code / tax code (MST)': { id: 'Kode perusahaan / kode pajak (MST)', zh: '企业代码 / 税号（MST）' },
  'Citizen identity card number': { id: 'Nomor kartu identitas warga', zh: '公民身份证号' },
  'Philippines': { id: 'Filipina', zh: '菲律宾' },
  'BIR Taxpayer Identification Number (TIN)': { id: 'BIR Taxpayer Identification Number (TIN)', zh: 'BIR 纳税人识别号（TIN）' },
  'SEC registration number': { id: 'Nomor registrasi SEC', zh: 'SEC 注册号' },
  'DTI business name registration (sole proprietors)': { id: 'Registrasi nama usaha DTI (usaha perseorangan)', zh: 'DTI 商号登记（个体经营者）' },
  'India': { id: 'India', zh: '印度' },
  'Permanent Account Number (PAN)': { id: 'Permanent Account Number (PAN)', zh: '永久账号（PAN）' },
  'GSTIN': { id: 'GSTIN', zh: 'GST 识别号（GSTIN）' },
  'Corporate Identification Number (CIN)': { id: 'Corporate Identification Number (CIN)', zh: '公司识别号（CIN）' },
  'Aadhaar number': { id: 'Nomor Aadhaar', zh: 'Aadhaar 身份号' },
  'Japan': { id: 'Jepang', zh: '日本' },
  'Corporate Number (Hojin Bango)': { id: 'Corporate Number (Hojin Bango)', zh: '法人番号' },
  'Qualified invoice issuer registration number': { id: 'Nomor registrasi penerbit invoice resmi', zh: '合格发票开具人登记号' },
  'My Number': { id: 'My Number', zh: '个人番号（My Number）' },
  'South Korea': { id: 'Korea Selatan', zh: '韩国' },
  'Business Registration Number': { id: 'Nomor Registrasi Usaha', zh: '营业登记号' },
  'Corporate Registration Number': { id: 'Nomor Registrasi Badan Hukum', zh: '法人登记号' },
  'Resident Registration Number': { id: 'Nomor Registrasi Penduduk', zh: '居民登记号' },
  'China (Mainland)': { id: 'Tiongkok (Daratan)', zh: '中国（内地）' },
  'Unified Social Credit Code (USCC)': { id: 'Unified Social Credit Code (USCC)', zh: '统一社会信用代码' },
  'Resident identity card number': { id: 'Nomor kartu identitas penduduk', zh: '居民身份证号码' },
  'Hong Kong SAR': { id: 'Hong Kong SAR', zh: '中国香港特别行政区' },
  'Business Registration Number (BRN)': { id: 'Business Registration Number (BRN)', zh: '商业登记号（BRN）' },
  'Company Registration Number (CRN)': { id: 'Company Registration Number (CRN)', zh: '公司注册编号（CRN）' },
  'HKID number': { id: 'Nomor HKID', zh: '香港身份证号码' },
  'United Arab Emirates': { id: 'Uni Emirat Arab', zh: '阿拉伯联合酋长国' },
  'Tax Registration Number (TRN)': { id: 'Tax Registration Number (TRN)', zh: '税务登记号（TRN）' },
  'Trade licence number': { id: 'Nomor izin dagang', zh: '营业执照号' },
  'Emirates ID': { id: 'Emirates ID', zh: '阿联酋身份证' },
  'Institutional Lender': { id: 'Pemberi Dana Institusi', zh: '机构出借人' },
  'Channeling Bank / Multifinance': { id: 'Bank Channeling / Multifinance', zh: '助贷银行 / 多元融资公司' },
  'Collection Agency': { id: 'Agen Penagihan', zh: '催收机构' },
  'Credit Bureau / Scoring Provider': { id: 'Biro Kredit / Penyedia Scoring', zh: '征信机构 / 评分服务商' },
  'e-KYC Provider': { id: 'Penyedia e-KYC', zh: '电子 KYC 服务商' },
  'Payment & Virtual Account Provider': { id: 'Penyedia Pembayaran & Virtual Account', zh: '支付与虚拟账户服务商' },
  'Credit Insurance Provider': { id: 'Penyedia Asuransi Kredit', zh: '信用保险提供方' },
  'Marketing Affiliate': { id: 'Afiliasi Pemasaran', zh: '营销联盟' },
  'Peer-to-peer lending / fintech lending regulation of the operating country': { id: 'Regulasi pinjaman P2P / fintech lending di negara operasional', zh: '经营所在国的 P2P 借贷 / 金融科技借贷监管规定' },
  'FATF Recommendations (AML/CFT)': { id: 'Rekomendasi FATF (APU-PPT)', zh: 'FATF 建议（反洗钱 / 反恐融资）' },
  'Responsible lending & fair collection conduct': { id: 'Pemberian pinjaman yang bertanggung jawab & penagihan yang wajar', zh: '负责任放贷与公平催收行为' },
  'Personal data protection & data localisation rules': { id: 'Perlindungan data pribadi & aturan lokalisasi data', zh: '个人数据保护与数据本地化规定' },
  'ISO/IEC 27001 information security': { id: 'ISO/IEC 27001 keamanan informasi', zh: 'ISO/IEC 27001 信息安全' },
  'Merchant': { id: 'Merchant', zh: '商户' },
  'Acquiring Bank': { id: 'Bank Acquirer', zh: '收单银行' },
  'Issuing Bank': { id: 'Bank Penerbit', zh: '发卡银行' },
  'Card Scheme / Network': { id: 'Card Scheme / Jaringan', zh: '卡组织 / 网络' },
  'E-wallet Operator': { id: 'Operator E-wallet', zh: '电子钱包运营商' },
  'Switching Network': { id: 'Jaringan Switching', zh: '转接网络' },
  'Fraud & Risk Vendor': { id: 'Vendor Fraud & Risiko', zh: '反欺诈与风控供应商' },
  'Aggregator / Reseller': { id: 'Agregator / Reseller', zh: '聚合商 / 代理商' },
  'PCI DSS': { id: 'PCI DSS', zh: 'PCI DSS' },
  'EMVCo & card scheme operating rules': { id: 'EMVCo & aturan operasional card scheme', zh: 'EMVCo 及卡组织运营规则' },
  'Payment system & e-money regulation of the operating country': { id: 'Regulasi sistem pembayaran & uang elektronik di negara operasional', zh: '经营所在国的支付系统与电子货币监管规定' },
  'Core Banking Vendor': { id: 'Vendor Core Banking', zh: '核心银行系统供应商' },
  'Custodian Bank': { id: 'Bank Kustodian', zh: '托管银行' },
  'Broker-Dealer': { id: 'Perantara Pedagang Efek', zh: '证券经纪自营商' },
  'Fund Manager': { id: 'Manajer Investasi', zh: '基金管理人' },
  'Selling Agent': { id: 'Agen Penjual', zh: '销售代理' },
  'Credit Bureau': { id: 'Biro Kredit', zh: '征信机构' },
  'Cloud Provider': { id: 'Penyedia Cloud', zh: '云服务商' },
  'KYC Provider': { id: 'Penyedia KYC', zh: 'KYC 服务商' },
  'Banking & capital markets regulation of the operating country': { id: 'Regulasi perbankan & pasar modal di negara operasional', zh: '经营所在国的银行与资本市场监管规定' },
  'Basel Committee principles (operational resilience, BCBS 239)': { id: 'Prinsip Komite Basel (ketahanan operasional, BCBS 239)', zh: '巴塞尔委员会原则（运营韧性、BCBS 239）' },
  'FATCA / CRS reporting': { id: 'Pelaporan FATCA / CRS', zh: 'FATCA / CRS 申报' },
  'Outsourcing & third-party risk management guidelines': { id: 'Pedoman alih daya & manajemen risiko pihak ketiga', zh: '外包与第三方风险管理指引' },
  'Enterprise Customer': { id: 'Pelanggan Korporat', zh: '企业客户' },
  'Cloud Infrastructure': { id: 'Infrastruktur Cloud', zh: '云基础设施' },
  'Reseller': { id: 'Reseller', zh: '代理商' },
  'Systems Integrator': { id: 'System Integrator', zh: '系统集成商' },
  'Sub-processor': { id: 'Sub-pemroses', zh: '子处理者' },
  'Payment Provider': { id: 'Penyedia Pembayaran', zh: '支付服务商' },
  'SOC 2 Type II': { id: 'SOC 2 Type II', zh: 'SOC 2 Type II' },
  'Personal data protection law of the operating country (GDPR where EU data is processed)': { id: 'UU perlindungan data pribadi negara operasional (GDPR bila memproses data UE)', zh: '经营所在国的个人数据保护法（处理欧盟数据时适用 GDPR）' },
  'Cross-border data transfer rules': { id: 'Aturan transfer data lintas negara', zh: '跨境数据传输规定' },
  'OWASP ASVS secure development': { id: 'Pengembangan aman OWASP ASVS', zh: 'OWASP ASVS 安全开发' },
  'Software House': { id: 'Software House', zh: '软件公司' },
  'Freelance Developer': { id: 'Developer Freelance', zh: '自由职业开发者' },
  'QA / Testing Vendor': { id: 'Vendor QA / Pengujian', zh: '质量保证 / 测试供应商' },
  'Managed Service Provider': { id: 'Managed Service Provider', zh: '托管服务提供商' },
  'Customer': { id: 'Pelanggan', zh: '客户' },
  'ISO/IEC 25010 software quality': { id: 'ISO/IEC 25010 kualitas perangkat lunak', zh: 'ISO/IEC 25010 软件质量' },
  'OWASP Top 10 / ASVS': { id: 'OWASP Top 10 / ASVS', zh: 'OWASP Top 10 / ASVS' },
  'Open-source licence compliance (SPDX)': { id: 'Kepatuhan lisensi open-source (SPDX)', zh: '开源许可证合规（SPDX）' },
  'Personal data protection law of the operating country': { id: 'UU perlindungan data pribadi negara operasional', zh: '经营所在国的个人数据保护法' },
  'Influencer / KOL': { id: 'Influencer / KOL', zh: '网红 / KOL' },
  'Talent Management Agency': { id: 'Agensi Manajemen Talenta', zh: '达人经纪机构' },
  'Content Creator': { id: 'Kreator Konten', zh: '内容创作者' },
  'Affiliate': { id: 'Afiliasi', zh: '联盟推广者' },
  'Brand / Advertiser': { id: 'Brand / Pengiklan', zh: '品牌 / 广告主' },
  'Multi-channel Network (MCN)': { id: 'Multi-channel Network (MCN)', zh: '多频道网络（MCN）' },
  'Advertising standards & paid-content disclosure rules (#ad / sponsored labels)': { id: 'Standar periklanan & aturan pengungkapan konten berbayar (label #ad / sponsored)', zh: '广告标准与付费内容披露规则（#广告 / 赞助标注）' },
  'Consumer protection law': { id: 'UU perlindungan konsumen', zh: '消费者保护法' },
  'Platform policies (Meta, TikTok, YouTube)': { id: 'Kebijakan platform (Meta, TikTok, YouTube)', zh: '平台政策（Meta、TikTok、YouTube）' },
  'Copyright & image rights': { id: 'Hak cipta & hak atas citra', zh: '版权与肖像权' },
  'Advertising': { id: 'Periklanan', zh: '广告' },
  'Media Placement': { id: 'Penempatan Media', zh: '媒体投放' },
  'AdTech': { id: 'AdTech', zh: '广告技术' },
  'Content': { id: 'Konten', zh: '内容' },
  'Production House': { id: 'Production House', zh: '制作公司' },
  'Talent': { id: 'Talenta', zh: '达人' },
  'Agency': { id: 'Agensi', zh: '代理机构' },
  'Advertising standards codes': { id: 'Kode etik standar periklanan', zh: '广告标准准则' },
  'Broadcasting & content classification rules': { id: 'Aturan penyiaran & klasifikasi konten', zh: '广播与内容分级规定' },
  'Copyright & neighbouring rights law': { id: 'UU hak cipta & hak terkait', zh: '版权及邻接权法' },
  'IAB / MRC viewability & measurement standards': { id: 'Standar viewability & pengukuran IAB / MRC', zh: 'IAB / MRC 可见度与测量标准' },
  'Brand safety frameworks': { id: 'Kerangka brand safety', zh: '品牌安全框架' },
  'Medical Device Supplier': { id: 'Pemasok Alat Kesehatan', zh: '医疗器械供应商' },
  'Pharmaceutical Distributor': { id: 'Distributor Farmasi', zh: '药品经销商' },
  'Doctor / Specialist': { id: 'Dokter / Spesialis', zh: '医生 / 专科医生' },
  'Insurance / Payer': { id: 'Asuransi / Pembayar', zh: '保险 / 支付方' },
  'Laboratory': { id: 'Laboratorium', zh: '实验室' },
  'Medical Waste Processor': { id: 'Pengolah Limbah Medis', zh: '医疗废物处理商' },
  'Facility Services': { id: 'Layanan Fasilitas', zh: '设施服务' },
  'Health facility licensing & hospital accreditation (e.g. JCI, national accreditation)': { id: 'Perizinan fasilitas kesehatan & akreditasi rumah sakit (mis. JCI, akreditasi nasional)', zh: '医疗机构许可与医院认证（如 JCI、国家认证）' },
  'Good Distribution Practice for medicines & devices': { id: 'Cara Distribusi yang Baik untuk obat & alat kesehatan', zh: '药品与医疗器械良好分销规范' },
  'ISO 13485 (medical devices)': { id: 'ISO 13485 (alat kesehatan)', zh: 'ISO 13485（医疗器械）' },
  'Patient data confidentiality rules': { id: 'Aturan kerahasiaan data pasien', zh: '患者数据保密规定' },
  'Hazardous / medical waste regulations': { id: 'Regulasi limbah B3 / medis', zh: '危险 / 医疗废物法规' },
  'Doctor / Clinic': { id: 'Dokter / Klinik', zh: '医生 / 诊所' },
  'Pharmacy': { id: 'Apotek', zh: '药房' },
  'Insurer': { id: 'Perusahaan Asuransi', zh: '保险公司' },
  'Corporate Client': { id: 'Klien Korporat', zh: '企业客户' },
  'Cloud & Health IT Vendor': { id: 'Vendor Cloud & IT Kesehatan', zh: '云与医疗 IT 供应商' },
  'Telemedicine & digital health regulation of the operating country': { id: 'Regulasi telemedisin & kesehatan digital di negara operasional', zh: '经营所在国的远程医疗与数字健康监管规定' },
  'Health data confidentiality & personal data protection': { id: 'Kerahasiaan data kesehatan & perlindungan data pribadi', zh: '健康数据保密与个人数据保护' },
  'ISO/IEC 27001 & ISO 27799 (health information security)': { id: 'ISO/IEC 27001 & ISO 27799 (keamanan informasi kesehatan)', zh: 'ISO/IEC 27001 与 ISO 27799（健康信息安全）' },
  'HL7 FHIR interoperability': { id: 'Interoperabilitas HL7 FHIR', zh: 'HL7 FHIR 互操作性' },
  'Electronic prescription rules': { id: 'Aturan resep elektronik', zh: '电子处方规定' },
  'Merchant / Seller': { id: 'Merchant / Penjual', zh: '商户 / 卖家' },
  'Brand Principal': { id: 'Prinsipal Merek', zh: '品牌方' },
  'Logistics Provider': { id: 'Penyedia Logistik', zh: '物流服务商' },
  'Advertising Partner': { id: 'Mitra Periklanan', zh: '广告合作伙伴' },
  'E-commerce / electronic trading regulation of the operating country': { id: 'Regulasi e-commerce / perdagangan elektronik di negara operasional', zh: '经营所在国的电子商务 / 电子交易监管规定' },
  'Product safety & labelling standards': { id: 'Standar keamanan & pelabelan produk', zh: '产品安全与标签标准' },
  'Notice-and-takedown for IP infringement': { id: 'Notice-and-takedown untuk pelanggaran HKI', zh: '知识产权侵权通知删除机制' },
  'Personal data protection law': { id: 'UU perlindungan data pribadi', zh: '个人数据保护法' },
  'Franchisee': { id: 'Franchisee', zh: '加盟商' },
  'Master Franchisee': { id: 'Master Franchisee', zh: '区域总加盟商' },
  'Supplier': { id: 'Pemasok', zh: '供应商' },
  'Distributor': { id: 'Distributor', zh: '经销商' },
  'Landlord': { id: 'Pemilik Properti', zh: '业主' },
  'Franchise registration & disclosure regulation of the operating country': { id: 'Regulasi pendaftaran & keterbukaan waralaba di negara operasional', zh: '经营所在国的特许经营登记与信息披露规定' },
  'Trademark law': { id: 'UU merek', zh: '商标法' },
  'Competition law (resale price maintenance, exclusivity)': { id: 'UU persaingan usaha (penetapan harga jual kembali, eksklusivitas)', zh: '竞争法（转售价格维持、排他）' },
  'Consumer protection & product labelling': { id: 'Perlindungan konsumen & pelabelan produk', zh: '消费者保护与产品标签' },
  'Food safety / halal certification where applicable': { id: 'Keamanan pangan / sertifikasi halal bila berlaku', zh: '食品安全 / 清真认证（如适用）' },
  'Modern Retailer': { id: 'Ritel Modern', zh: '现代零售商' },
  'Marketplace': { id: 'Marketplace', zh: '电商平台' },
  'Contract Manufacturer': { id: 'Produsen Maklon', zh: '代工厂' },
  'Fulfilment Partner': { id: 'Mitra Fulfilment', zh: '仓配履约合作伙伴' },
  'Promotion Agency': { id: 'Agensi Promosi', zh: '促销代理' },
  'Customer Service BPO': { id: 'BPO Layanan Pelanggan', zh: '客服外包（BPO）' },
  'Product registration & labelling (food, cosmetics, household)': { id: 'Registrasi & pelabelan produk (pangan, kosmetik, rumah tangga)', zh: '产品注册与标签（食品、化妆品、家居用品）' },
  'Halal certification rules where applicable': { id: 'Aturan sertifikasi halal bila berlaku', zh: '清真认证规定（如适用）' },
  'Competition law on distribution & pricing': { id: 'UU persaingan usaha terkait distribusi & harga', zh: '有关分销与定价的竞争法' },
  'Personal data protection for CRM & loyalty data': { id: 'Perlindungan data pribadi untuk data CRM & loyalitas', zh: 'CRM 与会员数据的个人数据保护' },
  'Law Firm': { id: 'Firma Hukum', zh: '律师事务所' },
  'Consultant': { id: 'Konsultan', zh: '顾问' },
  'Audit Firm': { id: 'Kantor Akuntan Publik', zh: '会计师事务所' },
  'Tax Advisor': { id: 'Konsultan Pajak', zh: '税务顾问' },
  'Notary': { id: 'Notaris', zh: '公证人' },
  'Expert / Specialist': { id: 'Ahli / Spesialis', zh: '专家 / 专业人士' },
  'Client': { id: 'Klien', zh: '客户' },
  'Professional conduct rules of bar associations & professional bodies': { id: 'Kode etik profesi organisasi advokat & asosiasi profesi', zh: '律师协会及专业团体的职业行为规范' },
  'Legal professional privilege & confidentiality': { id: 'Hak istimewa profesi hukum & kerahasiaan', zh: '法律职业特权与保密' },
  'AML/CFT duties of gatekeeper professions (FATF R.22)': { id: 'Kewajiban APU-PPT profesi gatekeeper (FATF R.22)', zh: '“守门人”职业的反洗钱 / 反恐融资义务（FATF 建议 22）' },
  'Anti-bribery & corruption laws': { id: 'UU antisuap & antikorupsi', zh: '反贿赂与反腐败法' },
  'Client / Advertiser': { id: 'Klien / Pengiklan', zh: '客户 / 广告主' },
  'Ad Platform': { id: 'Platform Iklan', zh: '广告平台' },
  'Media Owner': { id: 'Pemilik Media', zh: '媒体主' },
  'Freelancer': { id: 'Freelancer', zh: '自由职业者' },
  'MarTech Vendor': { id: 'Vendor MarTech', zh: '营销技术供应商' },
  'Advertising standards & disclosure rules': { id: 'Standar periklanan & aturan pengungkapan', zh: '广告标准与披露规则' },
  'Ad platform policies (Google, Meta, TikTok)': { id: 'Kebijakan platform iklan (Google, Meta, TikTok)', zh: '广告平台政策（Google、Meta、TikTok）' },
  'Cookie / tracking consent & personal data protection': { id: 'Persetujuan cookie / pelacakan & perlindungan data pribadi', zh: 'Cookie / 追踪同意与个人数据保护' },
  'IAB / MRC measurement standards': { id: 'Standar pengukuran IAB / MRC', zh: 'IAB / MRC 测量标准' },
  'Copyright in creative works': { id: 'Hak cipta atas karya kreatif', zh: '创意作品版权' },
  'Client / Employer': { id: 'Klien / Pemberi Kerja', zh: '客户 / 雇主' },
  'Executive Search Firm': { id: 'Firma Executive Search', zh: '高管猎头公司' },
  'Staffing Agency': { id: 'Agen Penyalur Tenaga Kerja', zh: '人力派遣机构' },
  'Job Board': { id: 'Portal Lowongan Kerja', zh: '招聘网站' },
  'Background Screening Provider': { id: 'Penyedia Background Screening', zh: '背景调查服务商' },
  'Candidate': { id: 'Kandidat', zh: '候选人' },
  'Labour & employment law (outsourcing, fixed-term contracts)': { id: 'UU ketenagakerjaan (alih daya, PKWT)', zh: '劳动与雇佣法（外包、固定期限合同）' },
  'ILO Private Employment Agencies Convention (C181) principles': { id: 'Prinsip Konvensi ILO tentang Agen Tenaga Kerja Swasta (C181)', zh: '国际劳工组织《私营就业机构公约》（C181）原则' },
  'Anti-discrimination in hiring': { id: 'Antidiskriminasi dalam rekrutmen', zh: '招聘反歧视' },
  'Candidate personal data protection': { id: 'Perlindungan data pribadi kandidat', zh: '候选人个人数据保护' },
  'Social security contribution rules': { id: 'Aturan iuran jaminan sosial', zh: '社会保险缴费规定' },
  'Carrier (Sea / Air / Land)': { id: 'Pengangkut (Laut / Udara / Darat)', zh: '承运人（海运 / 空运 / 陆运）' },
  'Freight Forwarder': { id: 'Freight Forwarder', zh: '货运代理' },
  'Shipping Line': { id: 'Perusahaan Pelayaran', zh: '航运公司' },
  'Customs Broker': { id: 'PPJK / Customs Broker', zh: '报关行' },
  'Warehouse Operator': { id: 'Operator Gudang', zh: '仓储运营商' },
  'Trucking Company': { id: 'Perusahaan Truk', zh: '卡车运输公司' },
  'Incoterms® 2020': { id: 'Incoterms® 2020', zh: 'Incoterms® 2020 国际贸易术语' },
  'Carrier liability conventions (Hague-Visby, Montreal, CMR)': { id: 'Konvensi tanggung jawab pengangkut (Hague-Visby, Montreal, CMR)', zh: '承运人责任公约（海牙-维斯比、蒙特利尔、CMR）' },
  'Customs & Authorised Economic Operator (AEO) programmes': { id: 'Program kepabeanan & Authorised Economic Operator (AEO)', zh: '海关与经认证的经营者（AEO）计划' },
  'Dangerous goods rules (IMDG, IATA DGR)': { id: 'Aturan barang berbahaya (IMDG, IATA DGR)', zh: '危险品规则（IMDG、IATA DGR）' },
  'Export control & sanctions regimes': { id: 'Rezim kontrol ekspor & sanksi', zh: '出口管制与制裁制度' },
  'Cold Storage Operator': { id: 'Operator Cold Storage', zh: '冷库运营商' },
  'Reefer Transport': { id: 'Transportasi Berpendingin', zh: '冷藏运输' },
  'Food / Pharma Principal': { id: 'Prinsipal Pangan / Farmasi', zh: '食品 / 药品品牌方' },
  'Monitoring / IoT Vendor': { id: 'Vendor Monitoring / IoT', zh: '监测 / 物联网供应商' },
  'Equipment Maintenance Contractor': { id: 'Kontraktor Perawatan Peralatan', zh: '设备维护承包商' },
  'WHO Good Distribution Practice for pharmaceuticals': { id: 'Cara Distribusi yang Baik WHO untuk farmasi', zh: '世卫组织药品良好分销规范' },
  'HACCP / ISO 22000 food safety': { id: 'Keamanan pangan HACCP / ISO 22000', zh: 'HACCP / ISO 22000 食品安全' },
  'ISO 23412 refrigerated parcel delivery': { id: 'ISO 23412 pengiriman paket berpendingin', zh: 'ISO 23412 冷藏包裹配送' },
  'Refrigerant & environmental regulations': { id: 'Regulasi refrigeran & lingkungan', zh: '制冷剂与环境法规' },
  'Halal logistics where applicable': { id: 'Logistik halal bila berlaku', zh: '清真物流（如适用）' },
  'Courier / 3PL': { id: 'Kurir / 3PL', zh: '快递 / 第三方物流' },
  'Driver Partner': { id: 'Mitra Pengemudi', zh: '司机合作伙伴' },
  'Fleet Leasing Company': { id: 'Perusahaan Sewa Armada', zh: '车队租赁公司' },
  'Vehicle Workshop': { id: 'Bengkel Kendaraan', zh: '汽车维修厂' },
  'Fuel / EV Charging Provider': { id: 'Penyedia BBM / Pengisian EV', zh: '燃油 / 电动车充电服务商' },
  'Road traffic & transport licensing rules': { id: 'Aturan lalu lintas jalan & perizinan angkutan', zh: '道路交通与运输许可规定' },
  'Postal / courier regulation': { id: 'Regulasi pos / kurir', zh: '邮政 / 快递监管规定' },
  'Occupational safety for drivers': { id: 'Keselamatan kerja pengemudi', zh: '司机职业安全' },
  'Gig-worker / partnership labour rules': { id: 'Aturan ketenagakerjaan pekerja gig / kemitraan', zh: '零工 / 合作用工规定' },
  'Personal data protection (recipient data, tracking)': { id: 'Perlindungan data pribadi (data penerima, pelacakan)', zh: '个人数据保护（收件人数据、追踪）' },
  'Government Authority': { id: 'Otoritas Pemerintah', zh: '政府主管部门' },
  'Operator': { id: 'Operator', zh: '运营商' },
  'Vehicle / Rolling Stock Supplier': { id: 'Pemasok Kendaraan / Sarana Perkeretaapian', zh: '车辆 / 机车车辆供应商' },
  'Ticketing System Vendor': { id: 'Vendor Sistem Tiket', zh: '票务系统供应商' },
  'Maintenance Contractor': { id: 'Kontraktor Perawatan', zh: '维护承包商' },
  'Concessionaire': { id: 'Pemegang Konsesi', zh: '特许经营者' },
  'Transport safety regulation of the operating country': { id: 'Regulasi keselamatan transportasi di negara operasional', zh: '经营所在国的运输安全监管规定' },
  'ISO 39001 road traffic safety': { id: 'ISO 39001 keselamatan lalu lintas jalan', zh: 'ISO 39001 道路交通安全' },
  'Accessibility standards for public transport': { id: 'Standar aksesibilitas transportasi publik', zh: '公共交通无障碍标准' },
  'Public procurement rules': { id: 'Aturan pengadaan barang/jasa pemerintah', zh: '政府采购规定' },
  'EMV / open-loop fare payment standards': { id: 'Standar pembayaran tarif EMV / open-loop', zh: 'EMV / 开环票款支付标准' },
  'EPC Contractor': { id: 'Kontraktor EPC', zh: 'EPC 总承包商' },
  'Equipment Supplier': { id: 'Pemasok Peralatan', zh: '设备供应商' },
  'Offtaker': { id: 'Offtaker', zh: '购电方 / 包销方' },
  'O&M Contractor': { id: 'Kontraktor O&M', zh: '运维承包商' },
  'Landowner': { id: 'Pemilik Lahan', zh: '土地所有者' },
  'Grid Operator / Utility': { id: 'Operator Jaringan / Utilitas', zh: '电网运营商 / 公用事业' },
  'Financier': { id: 'Pemberi Pembiayaan', zh: '融资方' },
  'IEC 61215 / 61730 (PV modules), IEC 61400 (wind turbines)': { id: 'IEC 61215 / 61730 (modul PV), IEC 61400 (turbin angin)', zh: 'IEC 61215 / 61730（光伏组件）、IEC 61400（风力发电机）' },
  'ISO 14001 & ISO 45001': { id: 'ISO 14001 & ISO 45001', zh: 'ISO 14001 与 ISO 45001' },
  'Grid code of the operating country': { id: 'Grid code negara operasional', zh: '经营所在国的电网规范' },
  'Environmental impact assessment rules': { id: 'Aturan analisis dampak lingkungan', zh: '环境影响评价规定' },
  'I-REC / renewable energy certificate standards': { id: 'Standar I-REC / sertifikat energi terbarukan', zh: 'I-REC / 可再生能源证书标准' },
  'Operator / Contractor (KKKS)': { id: 'Operator / Kontraktor (KKKS)', zh: '作业者 / 承包商（KKKS）' },
  'Drilling Contractor': { id: 'Kontraktor Pengeboran', zh: '钻井承包商' },
  'Oilfield Services Company': { id: 'Perusahaan Jasa Ladang Minyak', zh: '油田服务公司' },
  'Vessel Owner': { id: 'Pemilik Kapal', zh: '船东' },
  'API specifications & ISO 29001': { id: 'Spesifikasi API & ISO 29001', zh: 'API 规范与 ISO 29001' },
  'ISO 45001 & ISO 14001 (HSE)': { id: 'ISO 45001 & ISO 14001 (K3L)', zh: 'ISO 45001 与 ISO 14001（HSE）' },
  'IOGP safety guidelines': { id: 'Pedoman keselamatan IOGP', zh: 'IOGP 安全指南' },
  'MARPOL (marine pollution)': { id: 'MARPOL (pencemaran laut)', zh: 'MARPOL（防止船舶污染）' },
  'Upstream contracting & local content regulation of the operating country': { id: 'Regulasi kontrak hulu & TKDN di negara operasional', zh: '经营所在国的上游合同与本地成分监管规定' },
  'Government / Utility': { id: 'Pemerintah / Utilitas', zh: '政府 / 公用事业' },
  'Chemical Supplier': { id: 'Pemasok Bahan Kimia', zh: '化学品供应商' },
  'WHO guidelines for drinking-water quality': { id: 'Pedoman WHO untuk kualitas air minum', zh: '世卫组织饮用水水质准则' },
  'Effluent / wastewater discharge standards': { id: 'Baku mutu efluen / air limbah', zh: '出水 / 污水排放标准' },
  'ISO 24510 series (water services)': { id: 'Seri ISO 24510 (layanan air)', zh: 'ISO 24510 系列（水务服务）' },
  'ISO 14001': { id: 'ISO 14001', zh: 'ISO 14001' },
  'Public–private partnership regulation of the operating country': { id: 'Regulasi KPBU / kemitraan pemerintah-swasta di negara operasional', zh: '经营所在国的政府和社会资本合作（PPP）监管规定' },
  'University / Institution': { id: 'Universitas / Institusi', zh: '大学 / 机构' },
  'Research Partner': { id: 'Mitra Riset', zh: '科研合作伙伴' },
  'Funding Agency': { id: 'Lembaga Pendana', zh: '资助机构' },
  'EdTech Vendor': { id: 'Vendor EdTech', zh: '教育科技供应商' },
  'Content Provider': { id: 'Penyedia Konten', zh: '内容提供方' },
  'Trainer': { id: 'Pelatih', zh: '培训师' },
  'Facility Provider': { id: 'Penyedia Fasilitas', zh: '场地提供方' },
  'Accreditation standards for education providers': { id: 'Standar akreditasi penyelenggara pendidikan', zh: '教育机构认证标准' },
  'Research ethics for human subjects (Declaration of Helsinki)': { id: 'Etika riset pada manusia (Deklarasi Helsinki)', zh: '人体研究伦理（《赫尔辛基宣言》）' },
  'Student & minor data protection': { id: 'Perlindungan data siswa & anak', zh: '学生与未成年人数据保护' },
  'Institutional IP policy for research outputs': { id: 'Kebijakan HKI institusi atas luaran riset', zh: '机构对科研成果的知识产权政策' },
  'Export control on sensitive research': { id: 'Kontrol ekspor atas riset sensitif', zh: '敏感研究的出口管制' },
  'Individual Donor': { id: 'Donatur Perorangan', zh: '个人捐赠者' },
  'Corporate Donor': { id: 'Donatur Korporat', zh: '企业捐赠者' },
  'Grantee': { id: 'Penerima Hibah', zh: '受资助方' },
  'Foundation': { id: 'Yayasan', zh: '基金会' },
  'Fundraising Platform': { id: 'Platform Penggalangan Dana', zh: '筹款平台' },
  'Foundation / charity law of the operating country': { id: 'UU yayasan / amal di negara operasional', zh: '经营所在国的基金会 / 慈善法' },
  'Public fundraising permit rules': { id: 'Aturan izin pengumpulan uang/barang', zh: '公开募捐许可规定' },
  'FATF R.8 (non-profit organisations & terrorist financing)': { id: 'FATF R.8 (organisasi nirlaba & pendanaan terorisme)', zh: 'FATF 建议 8（非营利组织与恐怖融资）' },
  'Donor reporting & transparency standards': { id: 'Standar pelaporan & transparansi donatur', zh: '捐赠方报告与透明度标准' },
  'Zakat / religious giving rules where applicable': { id: 'Aturan zakat / donasi keagamaan bila berlaku', zh: '天课 / 宗教捐赠规定（如适用）' },
  'Donor': { id: 'Donor', zh: '捐赠方' },
  'Implementing Partner': { id: 'Mitra Pelaksana', zh: '执行伙伴' },
  'Sub-grantee': { id: 'Sub-penerima Hibah', zh: '次级受资助方' },
  'Relief Supplier': { id: 'Pemasok Bantuan', zh: '救援物资供应商' },
  'Government Agency': { id: 'Instansi Pemerintah', zh: '政府机构' },
  'UN Agency': { id: 'Badan PBB', zh: '联合国机构' },
  'Core Humanitarian Standard (CHS)': { id: 'Core Humanitarian Standard (CHS)', zh: '人道主义核心标准（CHS）' },
  'Sphere standards': { id: 'Standar Sphere', zh: 'Sphere 标准' },
  'PSEA / IASC safeguarding principles': { id: 'Prinsip perlindungan PSEA / IASC', zh: 'PSEA / IASC 保护原则' },
  'FATF R.8 & sanctions regimes': { id: 'FATF R.8 & rezim sanksi', zh: 'FATF 建议 8 与制裁制度' },
  'Humanitarian data protection (ICRC handbook)': { id: 'Perlindungan data kemanusiaan (buku pedoman ICRC)', zh: '人道主义数据保护（红十字国际委员会手册）' },
  'Office Supplies Vendor': { id: 'Vendor Alat Tulis Kantor', zh: '办公用品供应商' },
  'IT Hardware Reseller': { id: 'Reseller Perangkat Keras TI', zh: 'IT 硬件经销商' },
  'Software Licence Reseller': { id: 'Reseller Lisensi Perangkat Lunak', zh: '软件许可经销商' },
  'Facility Management': { id: 'Facility Management', zh: '设施管理' },
  'Cleaning & Security Services': { id: 'Jasa Kebersihan & Keamanan', zh: '保洁与安保服务' },
  'Catering Provider': { id: 'Penyedia Katering', zh: '餐饮服务商' },
  'Courier': { id: 'Kurir', zh: '快递' },
  'Internal procurement policy & delegation of authority': { id: 'Kebijakan pengadaan internal & pendelegasian wewenang', zh: '内部采购政策与授权体系' },
  'Anti-bribery management (ISO 37001)': { id: 'Manajemen antisuap (ISO 37001)', zh: '反贿赂管理（ISO 37001）' },
  'Labour law for outsourced services': { id: 'UU ketenagakerjaan untuk jasa alih daya', zh: '外包服务相关劳动法' },
  'Software licence compliance': { id: 'Kepatuhan lisensi perangkat lunak', zh: '软件许可合规' },
  'Sustainable procurement (ISO 20400)': { id: 'Pengadaan berkelanjutan (ISO 20400)', zh: '可持续采购（ISO 20400）' },
  'Tenant': { id: 'Penyewa', zh: '承租人' },
  'Property Manager': { id: 'Pengelola Properti', zh: '物业管理方' },
  'Building Management': { id: 'Pengelola Gedung', zh: '楼宇管理' },
  'Fit-out Contractor': { id: 'Kontraktor Fit-out', zh: '装修承包商' },
  'Real Estate Agent': { id: 'Agen Properti', zh: '房地产经纪' },
  'Land & property law of the operating country': { id: 'UU pertanahan & properti di negara operasional', zh: '经营所在国的土地与房地产法' },
  'Building safety & fire codes': { id: 'Kode keselamatan bangunan & kebakaran', zh: '建筑安全与消防规范' },
  'Strata / condominium rules': { id: 'Aturan strata / rumah susun', zh: '分层产权 / 公寓管理规定' },
  'AML rules for real estate transactions': { id: 'Aturan APU untuk transaksi properti', zh: '房地产交易反洗钱规定' },
  'Accessibility standards': { id: 'Standar aksesibilitas', zh: '无障碍标准' },
  'Freelance Platform': { id: 'Platform Freelance', zh: '自由职业平台' },
  'Employer of Record': { id: 'Employer of Record', zh: '名义雇主（EOR）' },
  'Contractor Agency': { id: 'Agensi Kontraktor', zh: '承包商中介' },
  'Employee vs independent contractor classification tests': { id: 'Uji klasifikasi karyawan vs kontraktor independen', zh: '雇员与独立承包商的定性测试' },
  'Minimum wage & working-time rules (if reclassified)': { id: 'Aturan upah minimum & waktu kerja (bila direklasifikasi)', zh: '最低工资与工时规定（如被重新定性）' },
  'Tax withholding for individuals': { id: 'Pemotongan pajak untuk perorangan', zh: '个人所得税代扣' },
  'Cross-border contractor payment & FX rules': { id: 'Aturan pembayaran kontraktor lintas negara & valas', zh: '跨境承包商付款与外汇规定' },
  'Service Provider': { id: 'Penyedia Jasa', zh: '服务提供方' },
  'Partner': { id: 'Mitra', zh: '合作伙伴' },
  'Commercial contract law of the operating country': { id: 'Hukum kontrak komersial negara operasional', zh: '经营所在国的商事合同法' },
  'Sanctions screening': { id: 'Penyaringan sanksi', zh: '制裁筛查' },
};
